settings:
  recovery:
    index: true
    events: false
    tools: false
  legacy:
    force: false
    interval: 0s
schema:
- name: kudaki-store-service
  path: .
  commands:
    clean:
      status: true
    run:
      status: true
  args:
    - -- KAFKA_BROKERS 178.62.107.160:29092
    - -- DB_PATH tcp(178.62.107.160:3306)
    - -- DB_USERNAME root
    - -- DB_PASSWORD mysqlrocks
    - -- DB_NAME kudaki_store
    - -- KAFKA_VERSION 2.1.1
    - -- REDISEARCH_SERVER 178.62.107.160:6379
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    scritps:
    - type: before
      command: taskkill /IM "kudaki-store-service.exe" /F