#!/bin/bash

docker build -t $IMAGE_NAME --build-arg KAFKA_BROKERS=$KAFKA_BROKERS --build-arg DB_PATH=$DB_PATH --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_NAME=$DB_NAME --build-arg KAFKA_VERSION=$KAFKA_VERSION .