// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/order.proto

package events

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	order "github.com/ilhammhdd/kudaki-storefront-service/entities/aggregates/order"
	user "github.com/ilhammhdd/kudaki-storefront-service/entities/aggregates/user"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//order service commands
type OrderServiceCommandTopic int32

const (
	OrderServiceCommandTopic_RETRIEVE_OWNERS_ORDER_HISTORIES  OrderServiceCommandTopic = 0
	OrderServiceCommandTopic_RETRIEVE_TENANTS_ORDER_HISTORIES OrderServiceCommandTopic = 1
	OrderServiceCommandTopic_OWNER_REVIEW_TENANT              OrderServiceCommandTopic = 2
	OrderServiceCommandTopic_TENANT_REVIEW_OWNER              OrderServiceCommandTopic = 3
	OrderServiceCommandTopic_TENANT_REVIEW_ITEMS              OrderServiceCommandTopic = 4
	OrderServiceCommandTopic_APPROVE_OWNER_ORDER              OrderServiceCommandTopic = 5
	OrderServiceCommandTopic_DISAPPROVE_OWNER_ORDER           OrderServiceCommandTopic = 6
	OrderServiceCommandTopic_CHECK_OUT                        OrderServiceCommandTopic = 7
)

var OrderServiceCommandTopic_name = map[int32]string{
	0: "RETRIEVE_OWNERS_ORDER_HISTORIES",
	1: "RETRIEVE_TENANTS_ORDER_HISTORIES",
	2: "OWNER_REVIEW_TENANT",
	3: "TENANT_REVIEW_OWNER",
	4: "TENANT_REVIEW_ITEMS",
	5: "APPROVE_OWNER_ORDER",
	6: "DISAPPROVE_OWNER_ORDER",
	7: "CHECK_OUT",
}

var OrderServiceCommandTopic_value = map[string]int32{
	"RETRIEVE_OWNERS_ORDER_HISTORIES":  0,
	"RETRIEVE_TENANTS_ORDER_HISTORIES": 1,
	"OWNER_REVIEW_TENANT":              2,
	"TENANT_REVIEW_OWNER":              3,
	"TENANT_REVIEW_ITEMS":              4,
	"APPROVE_OWNER_ORDER":              5,
	"DISAPPROVE_OWNER_ORDER":           6,
	"CHECK_OUT":                        7,
}

func (x OrderServiceCommandTopic) String() string {
	return proto.EnumName(OrderServiceCommandTopic_name, int32(x))
}

func (OrderServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{0}
}

//
//order service events
type OrderServiceEventTopic int32

const (
	OrderServiceEventTopic_OWNERS_ORDER_HISTORIES_RETRIEVED  OrderServiceEventTopic = 0
	OrderServiceEventTopic_TENANTS_ORDER_HISTORIES_RETRIEVED OrderServiceEventTopic = 1
	OrderServiceEventTopic_OWNER_REVIEWED_TENANT             OrderServiceEventTopic = 2
	OrderServiceEventTopic_TENANT_REVIEWED_OWNER             OrderServiceEventTopic = 3
	OrderServiceEventTopic_TENANT_REVIEWED_ITEMS             OrderServiceEventTopic = 4
	OrderServiceEventTopic_OWNER_ORDER_APPROVED              OrderServiceEventTopic = 5
	OrderServiceEventTopic_OWNER_ORDER_DISAPPROVED           OrderServiceEventTopic = 6
	OrderServiceEventTopic_CHECKED_OUT                       OrderServiceEventTopic = 7
	OrderServiceEventTopic_ORDER_APPROVED                    OrderServiceEventTopic = 8
	OrderServiceEventTopic_ORDER_DISAPPROVED                 OrderServiceEventTopic = 9
)

var OrderServiceEventTopic_name = map[int32]string{
	0: "OWNERS_ORDER_HISTORIES_RETRIEVED",
	1: "TENANTS_ORDER_HISTORIES_RETRIEVED",
	2: "OWNER_REVIEWED_TENANT",
	3: "TENANT_REVIEWED_OWNER",
	4: "TENANT_REVIEWED_ITEMS",
	5: "OWNER_ORDER_APPROVED",
	6: "OWNER_ORDER_DISAPPROVED",
	7: "CHECKED_OUT",
	8: "ORDER_APPROVED",
	9: "ORDER_DISAPPROVED",
}

var OrderServiceEventTopic_value = map[string]int32{
	"OWNERS_ORDER_HISTORIES_RETRIEVED":  0,
	"TENANTS_ORDER_HISTORIES_RETRIEVED": 1,
	"OWNER_REVIEWED_TENANT":             2,
	"TENANT_REVIEWED_OWNER":             3,
	"TENANT_REVIEWED_ITEMS":             4,
	"OWNER_ORDER_APPROVED":              5,
	"OWNER_ORDER_DISAPPROVED":           6,
	"CHECKED_OUT":                       7,
	"ORDER_APPROVED":                    8,
	"ORDER_DISAPPROVED":                 9,
}

func (x OrderServiceEventTopic) String() string {
	return proto.EnumName(OrderServiceEventTopic_name, int32(x))
}

func (OrderServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{1}
}

type RetrieveOwnersOrderHistories struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string            `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32             `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderStatus          order.OrderStatus `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3,enum=aggregates.order.OrderStatus" json:"order_status,omitempty"`
	ResultSchema         []byte            `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RetrieveOwnersOrderHistories) Reset()         { *m = RetrieveOwnersOrderHistories{} }
func (m *RetrieveOwnersOrderHistories) String() string { return proto.CompactTextString(m) }
func (*RetrieveOwnersOrderHistories) ProtoMessage()    {}
func (*RetrieveOwnersOrderHistories) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{0}
}

func (m *RetrieveOwnersOrderHistories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Unmarshal(m, b)
}
func (m *RetrieveOwnersOrderHistories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Marshal(b, m, deterministic)
}
func (m *RetrieveOwnersOrderHistories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveOwnersOrderHistories.Merge(m, src)
}
func (m *RetrieveOwnersOrderHistories) XXX_Size() int {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Size(m)
}
func (m *RetrieveOwnersOrderHistories) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveOwnersOrderHistories.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveOwnersOrderHistories proto.InternalMessageInfo

func (m *RetrieveOwnersOrderHistories) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveOwnersOrderHistories) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveOwnersOrderHistories) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveOwnersOrderHistories) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveOwnersOrderHistories) GetOrderStatus() order.OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return order.OrderStatus_PENDING
}

func (m *RetrieveOwnersOrderHistories) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type RetrieveTenantsOrderHistories struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string            `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32             `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderStatus          order.OrderStatus `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3,enum=aggregates.order.OrderStatus" json:"order_status,omitempty"`
	ResultSchema         []byte            `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RetrieveTenantsOrderHistories) Reset()         { *m = RetrieveTenantsOrderHistories{} }
func (m *RetrieveTenantsOrderHistories) String() string { return proto.CompactTextString(m) }
func (*RetrieveTenantsOrderHistories) ProtoMessage()    {}
func (*RetrieveTenantsOrderHistories) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{1}
}

func (m *RetrieveTenantsOrderHistories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Unmarshal(m, b)
}
func (m *RetrieveTenantsOrderHistories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Marshal(b, m, deterministic)
}
func (m *RetrieveTenantsOrderHistories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveTenantsOrderHistories.Merge(m, src)
}
func (m *RetrieveTenantsOrderHistories) XXX_Size() int {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Size(m)
}
func (m *RetrieveTenantsOrderHistories) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveTenantsOrderHistories.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveTenantsOrderHistories proto.InternalMessageInfo

func (m *RetrieveTenantsOrderHistories) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveTenantsOrderHistories) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveTenantsOrderHistories) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveTenantsOrderHistories) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveTenantsOrderHistories) GetOrderStatus() order.OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return order.OrderStatus_PENDING
}

func (m *RetrieveTenantsOrderHistories) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type OwnerReviewTenant struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	OrderUuid            string   `protobuf:"bytes,4,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerReviewTenant) Reset()         { *m = OwnerReviewTenant{} }
func (m *OwnerReviewTenant) String() string { return proto.CompactTextString(m) }
func (*OwnerReviewTenant) ProtoMessage()    {}
func (*OwnerReviewTenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{2}
}

func (m *OwnerReviewTenant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReviewTenant.Unmarshal(m, b)
}
func (m *OwnerReviewTenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReviewTenant.Marshal(b, m, deterministic)
}
func (m *OwnerReviewTenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReviewTenant.Merge(m, src)
}
func (m *OwnerReviewTenant) XXX_Size() int {
	return xxx_messageInfo_OwnerReviewTenant.Size(m)
}
func (m *OwnerReviewTenant) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReviewTenant.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReviewTenant proto.InternalMessageInfo

func (m *OwnerReviewTenant) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerReviewTenant) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *OwnerReviewTenant) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *OwnerReviewTenant) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

type TenantReviewOwner struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	OrderUuid            string   `protobuf:"bytes,4,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantReviewOwner) Reset()         { *m = TenantReviewOwner{} }
func (m *TenantReviewOwner) String() string { return proto.CompactTextString(m) }
func (*TenantReviewOwner) ProtoMessage()    {}
func (*TenantReviewOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{3}
}

func (m *TenantReviewOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewOwner.Unmarshal(m, b)
}
func (m *TenantReviewOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewOwner.Marshal(b, m, deterministic)
}
func (m *TenantReviewOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewOwner.Merge(m, src)
}
func (m *TenantReviewOwner) XXX_Size() int {
	return xxx_messageInfo_TenantReviewOwner.Size(m)
}
func (m *TenantReviewOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewOwner.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewOwner proto.InternalMessageInfo

func (m *TenantReviewOwner) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewOwner) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *TenantReviewOwner) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *TenantReviewOwner) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

type TenantReviewItems struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Review               string   `protobuf:"bytes,4,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantReviewItems) Reset()         { *m = TenantReviewItems{} }
func (m *TenantReviewItems) String() string { return proto.CompactTextString(m) }
func (*TenantReviewItems) ProtoMessage()    {}
func (*TenantReviewItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{4}
}

func (m *TenantReviewItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewItems.Unmarshal(m, b)
}
func (m *TenantReviewItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewItems.Marshal(b, m, deterministic)
}
func (m *TenantReviewItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewItems.Merge(m, src)
}
func (m *TenantReviewItems) XXX_Size() int {
	return xxx_messageInfo_TenantReviewItems.Size(m)
}
func (m *TenantReviewItems) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewItems.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewItems proto.InternalMessageInfo

func (m *TenantReviewItems) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewItems) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *TenantReviewItems) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *TenantReviewItems) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type ApproveOwnerOrder struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OwnerOrderUuid       string   `protobuf:"bytes,3,opt,name=owner_order_uuid,json=ownerOrderUuid,proto3" json:"owner_order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveOwnerOrder) Reset()         { *m = ApproveOwnerOrder{} }
func (m *ApproveOwnerOrder) String() string { return proto.CompactTextString(m) }
func (*ApproveOwnerOrder) ProtoMessage()    {}
func (*ApproveOwnerOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{5}
}

func (m *ApproveOwnerOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveOwnerOrder.Unmarshal(m, b)
}
func (m *ApproveOwnerOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveOwnerOrder.Marshal(b, m, deterministic)
}
func (m *ApproveOwnerOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveOwnerOrder.Merge(m, src)
}
func (m *ApproveOwnerOrder) XXX_Size() int {
	return xxx_messageInfo_ApproveOwnerOrder.Size(m)
}
func (m *ApproveOwnerOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveOwnerOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveOwnerOrder proto.InternalMessageInfo

func (m *ApproveOwnerOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ApproveOwnerOrder) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *ApproveOwnerOrder) GetOwnerOrderUuid() string {
	if m != nil {
		return m.OwnerOrderUuid
	}
	return ""
}

type DisapproveOwnerOrder struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OwnerOrderUuid       string   `protobuf:"bytes,3,opt,name=owner_order_uuid,json=ownerOrderUuid,proto3" json:"owner_order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisapproveOwnerOrder) Reset()         { *m = DisapproveOwnerOrder{} }
func (m *DisapproveOwnerOrder) String() string { return proto.CompactTextString(m) }
func (*DisapproveOwnerOrder) ProtoMessage()    {}
func (*DisapproveOwnerOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{6}
}

func (m *DisapproveOwnerOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisapproveOwnerOrder.Unmarshal(m, b)
}
func (m *DisapproveOwnerOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisapproveOwnerOrder.Marshal(b, m, deterministic)
}
func (m *DisapproveOwnerOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisapproveOwnerOrder.Merge(m, src)
}
func (m *DisapproveOwnerOrder) XXX_Size() int {
	return xxx_messageInfo_DisapproveOwnerOrder.Size(m)
}
func (m *DisapproveOwnerOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DisapproveOwnerOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DisapproveOwnerOrder proto.InternalMessageInfo

func (m *DisapproveOwnerOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DisapproveOwnerOrder) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *DisapproveOwnerOrder) GetOwnerOrderUuid() string {
	if m != nil {
		return m.OwnerOrderUuid
	}
	return ""
}

type CheckOut struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	CartUuid             string   `protobuf:"bytes,3,opt,name=cart_uuid,json=cartUuid,proto3" json:"cart_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckOut) Reset()         { *m = CheckOut{} }
func (m *CheckOut) String() string { return proto.CompactTextString(m) }
func (*CheckOut) ProtoMessage()    {}
func (*CheckOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{7}
}

func (m *CheckOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckOut.Unmarshal(m, b)
}
func (m *CheckOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckOut.Marshal(b, m, deterministic)
}
func (m *CheckOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckOut.Merge(m, src)
}
func (m *CheckOut) XXX_Size() int {
	return xxx_messageInfo_CheckOut.Size(m)
}
func (m *CheckOut) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckOut.DiscardUnknown(m)
}

var xxx_messageInfo_CheckOut proto.InternalMessageInfo

func (m *CheckOut) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CheckOut) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *CheckOut) GetCartUuid() string {
	if m != nil {
		return m.CartUuid
	}
	return ""
}

type OwnersOrderHistoriesRetrieved struct {
	Uid                          string                        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus                  *Status                       `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RetrieveOwnersOrderHistories *RetrieveOwnersOrderHistories `protobuf:"bytes,3,opt,name=retrieve_owners_order_histories,json=retrieveOwnersOrderHistories,proto3" json:"retrieve_owners_order_histories,omitempty"`
	Result                       []byte                        `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Owner                        *user.User                    `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	XXX_unrecognized             []byte                        `json:"-"`
	XXX_sizecache                int32                         `json:"-"`
}

func (m *OwnersOrderHistoriesRetrieved) Reset()         { *m = OwnersOrderHistoriesRetrieved{} }
func (m *OwnersOrderHistoriesRetrieved) String() string { return proto.CompactTextString(m) }
func (*OwnersOrderHistoriesRetrieved) ProtoMessage()    {}
func (*OwnersOrderHistoriesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{8}
}

func (m *OwnersOrderHistoriesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Unmarshal(m, b)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Marshal(b, m, deterministic)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnersOrderHistoriesRetrieved.Merge(m, src)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Size() int {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Size(m)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnersOrderHistoriesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_OwnersOrderHistoriesRetrieved proto.InternalMessageInfo

func (m *OwnersOrderHistoriesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnersOrderHistoriesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetRetrieveOwnersOrderHistories() *RetrieveOwnersOrderHistories {
	if m != nil {
		return m.RetrieveOwnersOrderHistories
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

type TenantOrderHistoriesRetrieved struct {
	Uid                           string                         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant                        *user.User                     `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus                   *Status                        `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RetrieveTenantsOrderHistories *RetrieveTenantsOrderHistories `protobuf:"bytes,5,opt,name=retrieve_tenants_order_histories,json=retrieveTenantsOrderHistories,proto3" json:"retrieve_tenants_order_histories,omitempty"`
	Result                        []byte                         `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                       `json:"-"`
	XXX_unrecognized              []byte                         `json:"-"`
	XXX_sizecache                 int32                          `json:"-"`
}

func (m *TenantOrderHistoriesRetrieved) Reset()         { *m = TenantOrderHistoriesRetrieved{} }
func (m *TenantOrderHistoriesRetrieved) String() string { return proto.CompactTextString(m) }
func (*TenantOrderHistoriesRetrieved) ProtoMessage()    {}
func (*TenantOrderHistoriesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{9}
}

func (m *TenantOrderHistoriesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Unmarshal(m, b)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Marshal(b, m, deterministic)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantOrderHistoriesRetrieved.Merge(m, src)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Size() int {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Size(m)
}
func (m *TenantOrderHistoriesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantOrderHistoriesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_TenantOrderHistoriesRetrieved proto.InternalMessageInfo

func (m *TenantOrderHistoriesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantOrderHistoriesRetrieved) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetRetrieveTenantsOrderHistories() *RetrieveTenantsOrderHistories {
	if m != nil {
		return m.RetrieveTenantsOrderHistories
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type OwnerReviewedTenant struct {
	Uid                  string             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User         `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Tenant               *user.User         `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status            `protobuf:"bytes,4,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Order                *order.Order       `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	OwnerReviewTenant    *OwnerReviewTenant `protobuf:"bytes,6,opt,name=owner_review_tenant,json=ownerReviewTenant,proto3" json:"owner_review_tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OwnerReviewedTenant) Reset()         { *m = OwnerReviewedTenant{} }
func (m *OwnerReviewedTenant) String() string { return proto.CompactTextString(m) }
func (*OwnerReviewedTenant) ProtoMessage()    {}
func (*OwnerReviewedTenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{10}
}

func (m *OwnerReviewedTenant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReviewedTenant.Unmarshal(m, b)
}
func (m *OwnerReviewedTenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReviewedTenant.Marshal(b, m, deterministic)
}
func (m *OwnerReviewedTenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReviewedTenant.Merge(m, src)
}
func (m *OwnerReviewedTenant) XXX_Size() int {
	return xxx_messageInfo_OwnerReviewedTenant.Size(m)
}
func (m *OwnerReviewedTenant) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReviewedTenant.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReviewedTenant proto.InternalMessageInfo

func (m *OwnerReviewedTenant) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerReviewedTenant) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OwnerReviewedTenant) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *OwnerReviewedTenant) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnerReviewedTenant) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OwnerReviewedTenant) GetOwnerReviewTenant() *OwnerReviewTenant {
	if m != nil {
		return m.OwnerReviewTenant
	}
	return nil
}

type TenantReviewedOwner struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User           `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Owner                *user.User           `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status              `protobuf:"bytes,4,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerFeedback        *order.OwnerFeedback `protobuf:"bytes,5,opt,name=owner_feedback,json=ownerFeedback,proto3" json:"owner_feedback,omitempty"`
	TenantReviewOwner    *TenantReviewOwner   `protobuf:"bytes,6,opt,name=tenant_review_owner,json=tenantReviewOwner,proto3" json:"tenant_review_owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TenantReviewedOwner) Reset()         { *m = TenantReviewedOwner{} }
func (m *TenantReviewedOwner) String() string { return proto.CompactTextString(m) }
func (*TenantReviewedOwner) ProtoMessage()    {}
func (*TenantReviewedOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{11}
}

func (m *TenantReviewedOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewedOwner.Unmarshal(m, b)
}
func (m *TenantReviewedOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewedOwner.Marshal(b, m, deterministic)
}
func (m *TenantReviewedOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewedOwner.Merge(m, src)
}
func (m *TenantReviewedOwner) XXX_Size() int {
	return xxx_messageInfo_TenantReviewedOwner.Size(m)
}
func (m *TenantReviewedOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewedOwner.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewedOwner proto.InternalMessageInfo

func (m *TenantReviewedOwner) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewedOwner) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantReviewedOwner) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *TenantReviewedOwner) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantReviewedOwner) GetOwnerFeedback() *order.OwnerFeedback {
	if m != nil {
		return m.OwnerFeedback
	}
	return nil
}

func (m *TenantReviewedOwner) GetTenantReviewOwner() *TenantReviewOwner {
	if m != nil {
		return m.TenantReviewOwner
	}
	return nil
}

type TenantReviewedItems struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	ItemFeedback         *order.ItemFeedback `protobuf:"bytes,4,opt,name=item_feedback,json=itemFeedback,proto3" json:"item_feedback,omitempty"`
	TenantReviewItems    *TenantReviewItems  `protobuf:"bytes,5,opt,name=tenant_review_items,json=tenantReviewItems,proto3" json:"tenant_review_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TenantReviewedItems) Reset()         { *m = TenantReviewedItems{} }
func (m *TenantReviewedItems) String() string { return proto.CompactTextString(m) }
func (*TenantReviewedItems) ProtoMessage()    {}
func (*TenantReviewedItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{12}
}

func (m *TenantReviewedItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewedItems.Unmarshal(m, b)
}
func (m *TenantReviewedItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewedItems.Marshal(b, m, deterministic)
}
func (m *TenantReviewedItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewedItems.Merge(m, src)
}
func (m *TenantReviewedItems) XXX_Size() int {
	return xxx_messageInfo_TenantReviewedItems.Size(m)
}
func (m *TenantReviewedItems) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewedItems.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewedItems proto.InternalMessageInfo

func (m *TenantReviewedItems) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewedItems) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantReviewedItems) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantReviewedItems) GetItemFeedback() *order.ItemFeedback {
	if m != nil {
		return m.ItemFeedback
	}
	return nil
}

func (m *TenantReviewedItems) GetTenantReviewItems() *TenantReviewItems {
	if m != nil {
		return m.TenantReviewItems
	}
	return nil
}

type OwnerOrderApproved struct {
	Uid                  string             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User         `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status            `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrder           *order.OwnerOrder  `protobuf:"bytes,4,opt,name=owner_order,json=ownerOrder,proto3" json:"owner_order,omitempty"`
	ApproveOwnerOrder    *ApproveOwnerOrder `protobuf:"bytes,5,opt,name=approve_owner_order,json=approveOwnerOrder,proto3" json:"approve_owner_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OwnerOrderApproved) Reset()         { *m = OwnerOrderApproved{} }
func (m *OwnerOrderApproved) String() string { return proto.CompactTextString(m) }
func (*OwnerOrderApproved) ProtoMessage()    {}
func (*OwnerOrderApproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{13}
}

func (m *OwnerOrderApproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerOrderApproved.Unmarshal(m, b)
}
func (m *OwnerOrderApproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerOrderApproved.Marshal(b, m, deterministic)
}
func (m *OwnerOrderApproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerOrderApproved.Merge(m, src)
}
func (m *OwnerOrderApproved) XXX_Size() int {
	return xxx_messageInfo_OwnerOrderApproved.Size(m)
}
func (m *OwnerOrderApproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerOrderApproved.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerOrderApproved proto.InternalMessageInfo

func (m *OwnerOrderApproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerOrderApproved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OwnerOrderApproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnerOrderApproved) GetOwnerOrder() *order.OwnerOrder {
	if m != nil {
		return m.OwnerOrder
	}
	return nil
}

func (m *OwnerOrderApproved) GetApproveOwnerOrder() *ApproveOwnerOrder {
	if m != nil {
		return m.ApproveOwnerOrder
	}
	return nil
}

type OwnerOrderDisapproved struct {
	Uid                  string                `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User            `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status               `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrder           *order.OwnerOrder     `protobuf:"bytes,4,opt,name=owner_order,json=ownerOrder,proto3" json:"owner_order,omitempty"`
	DisapproveOwnerOrder *DisapproveOwnerOrder `protobuf:"bytes,5,opt,name=disapprove_owner_order,json=disapproveOwnerOrder,proto3" json:"disapprove_owner_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OwnerOrderDisapproved) Reset()         { *m = OwnerOrderDisapproved{} }
func (m *OwnerOrderDisapproved) String() string { return proto.CompactTextString(m) }
func (*OwnerOrderDisapproved) ProtoMessage()    {}
func (*OwnerOrderDisapproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{14}
}

func (m *OwnerOrderDisapproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerOrderDisapproved.Unmarshal(m, b)
}
func (m *OwnerOrderDisapproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerOrderDisapproved.Marshal(b, m, deterministic)
}
func (m *OwnerOrderDisapproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerOrderDisapproved.Merge(m, src)
}
func (m *OwnerOrderDisapproved) XXX_Size() int {
	return xxx_messageInfo_OwnerOrderDisapproved.Size(m)
}
func (m *OwnerOrderDisapproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerOrderDisapproved.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerOrderDisapproved proto.InternalMessageInfo

func (m *OwnerOrderDisapproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerOrderDisapproved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OwnerOrderDisapproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnerOrderDisapproved) GetOwnerOrder() *order.OwnerOrder {
	if m != nil {
		return m.OwnerOrder
	}
	return nil
}

func (m *OwnerOrderDisapproved) GetDisapproveOwnerOrder() *DisapproveOwnerOrder {
	if m != nil {
		return m.DisapproveOwnerOrder
	}
	return nil
}

type CheckedOut struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	CheckOut             *CheckOut           `protobuf:"bytes,4,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Order                *order.Order        `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	OwnerOrders          []*order.OwnerOrder `protobuf:"bytes,6,rep,name=owner_orders,json=ownerOrders,proto3" json:"owner_orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CheckedOut) Reset()         { *m = CheckedOut{} }
func (m *CheckedOut) String() string { return proto.CompactTextString(m) }
func (*CheckedOut) ProtoMessage()    {}
func (*CheckedOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{15}
}

func (m *CheckedOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckedOut.Unmarshal(m, b)
}
func (m *CheckedOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckedOut.Marshal(b, m, deterministic)
}
func (m *CheckedOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckedOut.Merge(m, src)
}
func (m *CheckedOut) XXX_Size() int {
	return xxx_messageInfo_CheckedOut.Size(m)
}
func (m *CheckedOut) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckedOut.DiscardUnknown(m)
}

var xxx_messageInfo_CheckedOut proto.InternalMessageInfo

func (m *CheckedOut) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CheckedOut) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *CheckedOut) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *CheckedOut) GetCheckOut() *CheckOut {
	if m != nil {
		return m.CheckOut
	}
	return nil
}

func (m *CheckedOut) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *CheckedOut) GetOwnerOrders() []*order.OwnerOrder {
	if m != nil {
		return m.OwnerOrders
	}
	return nil
}

type OrderApproved struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrders          []*order.OwnerOrder `protobuf:"bytes,4,rep,name=owner_orders,json=ownerOrders,proto3" json:"owner_orders,omitempty"`
	Order                *order.Order        `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OrderApproved) Reset()         { *m = OrderApproved{} }
func (m *OrderApproved) String() string { return proto.CompactTextString(m) }
func (*OrderApproved) ProtoMessage()    {}
func (*OrderApproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{16}
}

func (m *OrderApproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderApproved.Unmarshal(m, b)
}
func (m *OrderApproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderApproved.Marshal(b, m, deterministic)
}
func (m *OrderApproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderApproved.Merge(m, src)
}
func (m *OrderApproved) XXX_Size() int {
	return xxx_messageInfo_OrderApproved.Size(m)
}
func (m *OrderApproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderApproved.DiscardUnknown(m)
}

var xxx_messageInfo_OrderApproved proto.InternalMessageInfo

func (m *OrderApproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrderApproved) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *OrderApproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrderApproved) GetOwnerOrders() []*order.OwnerOrder {
	if m != nil {
		return m.OwnerOrders
	}
	return nil
}

func (m *OrderApproved) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderDisapproved struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrders          []*order.OwnerOrder `protobuf:"bytes,4,rep,name=owner_orders,json=ownerOrders,proto3" json:"owner_orders,omitempty"`
	Order                *order.Order        `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OrderDisapproved) Reset()         { *m = OrderDisapproved{} }
func (m *OrderDisapproved) String() string { return proto.CompactTextString(m) }
func (*OrderDisapproved) ProtoMessage()    {}
func (*OrderDisapproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{17}
}

func (m *OrderDisapproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDisapproved.Unmarshal(m, b)
}
func (m *OrderDisapproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDisapproved.Marshal(b, m, deterministic)
}
func (m *OrderDisapproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDisapproved.Merge(m, src)
}
func (m *OrderDisapproved) XXX_Size() int {
	return xxx_messageInfo_OrderDisapproved.Size(m)
}
func (m *OrderDisapproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDisapproved.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDisapproved proto.InternalMessageInfo

func (m *OrderDisapproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrderDisapproved) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *OrderDisapproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrderDisapproved) GetOwnerOrders() []*order.OwnerOrder {
	if m != nil {
		return m.OwnerOrders
	}
	return nil
}

func (m *OrderDisapproved) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterEnum("event.OrderServiceCommandTopic", OrderServiceCommandTopic_name, OrderServiceCommandTopic_value)
	proto.RegisterEnum("event.OrderServiceEventTopic", OrderServiceEventTopic_name, OrderServiceEventTopic_value)
	proto.RegisterType((*RetrieveOwnersOrderHistories)(nil), "event.RetrieveOwnersOrderHistories")
	proto.RegisterType((*RetrieveTenantsOrderHistories)(nil), "event.RetrieveTenantsOrderHistories")
	proto.RegisterType((*OwnerReviewTenant)(nil), "event.OwnerReviewTenant")
	proto.RegisterType((*TenantReviewOwner)(nil), "event.TenantReviewOwner")
	proto.RegisterType((*TenantReviewItems)(nil), "event.TenantReviewItems")
	proto.RegisterType((*ApproveOwnerOrder)(nil), "event.ApproveOwnerOrder")
	proto.RegisterType((*DisapproveOwnerOrder)(nil), "event.DisapproveOwnerOrder")
	proto.RegisterType((*CheckOut)(nil), "event.CheckOut")
	proto.RegisterType((*OwnersOrderHistoriesRetrieved)(nil), "event.OwnersOrderHistoriesRetrieved")
	proto.RegisterType((*TenantOrderHistoriesRetrieved)(nil), "event.TenantOrderHistoriesRetrieved")
	proto.RegisterType((*OwnerReviewedTenant)(nil), "event.OwnerReviewedTenant")
	proto.RegisterType((*TenantReviewedOwner)(nil), "event.TenantReviewedOwner")
	proto.RegisterType((*TenantReviewedItems)(nil), "event.TenantReviewedItems")
	proto.RegisterType((*OwnerOrderApproved)(nil), "event.OwnerOrderApproved")
	proto.RegisterType((*OwnerOrderDisapproved)(nil), "event.OwnerOrderDisapproved")
	proto.RegisterType((*CheckedOut)(nil), "event.CheckedOut")
	proto.RegisterType((*OrderApproved)(nil), "event.OrderApproved")
	proto.RegisterType((*OrderDisapproved)(nil), "event.OrderDisapproved")
}

func init() { proto.RegisterFile("events/order.proto", fileDescriptor_8148e438de8b220f) }

var fileDescriptor_8148e438de8b220f = []byte{
	// 1188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x98, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0xd7, 0x4e, 0x13, 0x9a, 0x93, 0xa4, 0xeb, 0x4c, 0xbf, 0xb2, 0x6d, 0x43, 0xb3, 0x6e,
	0x57, 0xaa, 0x16, 0x9a, 0xa2, 0x72, 0x0d, 0x6c, 0x69, 0xbc, 0x6a, 0x84, 0x68, 0x96, 0x49, 0xba,
	0x2b, 0x21, 0x24, 0xcb, 0x8d, 0xa7, 0x8d, 0x69, 0x1d, 0x57, 0xf6, 0xb8, 0xcb, 0x1d, 0x6f, 0xc0,
	0x15, 0x12, 0x02, 0x89, 0x07, 0xe0, 0x86, 0xd7, 0xe0, 0x55, 0xe0, 0x16, 0xc1, 0x3d, 0x9a, 0x0f,
	0x27, 0x4e, 0xec, 0x34, 0x4d, 0xa1, 0x2b, 0xb1, 0x37, 0x55, 0xe7, 0xcc, 0xf1, 0x9c, 0xf3, 0xff,
	0xc5, 0xe7, 0x9c, 0x49, 0x00, 0x91, 0x6b, 0xd2, 0xa7, 0xc1, 0x9e, 0xe7, 0xdb, 0xc4, 0xaf, 0x5f,
	0xf9, 0x1e, 0xf5, 0x50, 0x96, 0xdb, 0xd6, 0x36, 0xac, 0xf3, 0x73, 0x9f, 0x9c, 0x5b, 0x94, 0xc8,
	0xed, 0xb8, 0xd3, 0xda, 0xa2, 0x7c, 0x30, 0xa0, 0x16, 0x0d, 0x03, 0x69, 0x5c, 0x8b, 0x3d, 0x12,
	0x06, 0xc4, 0xe7, 0x7f, 0xe4, 0xde, 0x93, 0xe4, 0x71, 0xaf, 0xfb, 0xc4, 0x37, 0xcf, 0x08, 0xb1,
	0x4f, 0xad, 0xee, 0x85, 0x74, 0xdb, 0x4e, 0xb8, 0x39, 0x94, 0xb8, 0xe3, 0x5e, 0xfa, 0x84, 0xc3,
	0x62, 0x19, 0xea, 0xbf, 0x2b, 0xb0, 0x81, 0x09, 0xf5, 0x1d, 0x72, 0x4d, 0x5a, 0x6c, 0x37, 0x68,
	0xb1, 0xdd, 0x23, 0x27, 0xa0, 0x9e, 0xef, 0x90, 0x00, 0x69, 0x90, 0x09, 0x1d, 0xbb, 0xa2, 0xd4,
	0x94, 0x9d, 0x3c, 0x66, 0xff, 0xa2, 0xc7, 0x50, 0xbc, 0x08, 0x6d, 0xeb, 0xc2, 0x31, 0xa9, 0x77,
	0x41, 0xfa, 0x15, 0x95, 0x6f, 0x15, 0x84, 0xad, 0xc3, 0x4c, 0x68, 0x05, 0x72, 0xde, 0xd9, 0x59,
	0x40, 0x68, 0x25, 0x53, 0x53, 0x76, 0xb2, 0x58, 0xae, 0xd0, 0x12, 0x64, 0x2f, 0x1d, 0xd7, 0xa1,
	0x95, 0x39, 0x6e, 0x16, 0x0b, 0xf4, 0x0c, 0x8a, 0x3c, 0x25, 0x53, 0x60, 0xaa, 0x64, 0x6b, 0xca,
	0xce, 0xc2, 0x7e, 0xb5, 0x3e, 0x4c, 0xbf, 0x2e, 0x52, 0xe6, 0xa9, 0xb5, 0xb9, 0x13, 0x2e, 0x78,
	0xc3, 0x05, 0xda, 0x82, 0x92, 0x4f, 0x82, 0xf0, 0x92, 0x9a, 0x41, 0xb7, 0x47, 0x5c, 0xab, 0x92,
	0xab, 0x29, 0x3b, 0x45, 0x5c, 0x14, 0xc6, 0x36, 0xb7, 0xe9, 0x7f, 0x28, 0x50, 0x8d, 0xa4, 0x76,
	0x48, 0xdf, 0xea, 0xd3, 0xb7, 0x57, 0xeb, 0xb7, 0x50, 0xe6, 0x9f, 0x26, 0x26, 0xd7, 0x0e, 0x79,
	0x2d, 0xd4, 0xde, 0x59, 0x9e, 0x6f, 0x51, 0xa7, 0x7f, 0xce, 0xe5, 0xa9, 0x58, 0xae, 0x50, 0x15,
	0x40, 0x08, 0x09, 0xd9, 0x99, 0x73, 0xfc, 0xc1, 0x3c, 0xb7, 0x9c, 0x84, 0x8e, 0xcd, 0x12, 0x10,
	0x51, 0x45, 0x06, 0x3c, 0x99, 0x37, 0x9a, 0xc0, 0x37, 0xa3, 0x09, 0x34, 0x29, 0x71, 0x83, 0xff,
	0x36, 0x01, 0x66, 0xe7, 0x67, 0xcb, 0xe0, 0x72, 0xa5, 0xfb, 0x50, 0x3e, 0xb8, 0xba, 0xf2, 0x3d,
	0x59, 0x50, 0xfc, 0x83, 0xbc, 0x5b, 0xe4, 0x1d, 0xd0, 0x62, 0x15, 0x2b, 0x84, 0x66, 0xb8, 0xdb,
	0x82, 0x37, 0x38, 0x9a, 0xab, 0x0d, 0x61, 0xa9, 0xe1, 0x04, 0xd6, 0x9b, 0x0e, 0xfb, 0x15, 0xcc,
	0x1f, 0xf6, 0x48, 0xf7, 0xa2, 0x15, 0xde, 0xf1, 0xed, 0x5a, 0x87, 0x7c, 0xd7, 0xf2, 0x69, 0x3c,
	0xc6, 0x3c, 0x33, 0xf0, 0xd3, 0xbf, 0x57, 0xa1, 0x9a, 0xd6, 0x93, 0xa2, 0x22, 0xb6, 0x53, 0x62,
	0x7e, 0x00, 0x45, 0xde, 0x73, 0xa3, 0xfa, 0x62, 0x31, 0x0b, 0xfb, 0xa5, 0x3a, 0x37, 0xd6, 0xa3,
	0x7a, 0xe2, 0x2b, 0x59, 0x4f, 0x5f, 0xc3, 0xa6, 0x2f, 0x0f, 0x34, 0xb9, 0xbc, 0x40, 0xea, 0xee,
	0x45, 0xf1, 0x78, 0x62, 0x85, 0xfd, 0x2d, 0x79, 0xc8, 0x4d, 0xed, 0x12, 0x6f, 0xf8, 0x37, 0x35,
	0x53, 0xfe, 0xca, 0xb0, 0x32, 0xe5, 0xaf, 0x4c, 0x11, 0xcb, 0x15, 0x7a, 0x0f, 0xb2, 0x3c, 0x34,
	0x6f, 0x07, 0x85, 0xfd, 0xe5, 0x78, 0x3b, 0xe0, 0xd3, 0xe1, 0x24, 0x20, 0x3e, 0x16, 0x3e, 0xfa,
	0x8f, 0x2a, 0x54, 0xc5, 0xab, 0x7d, 0x7b, 0x2c, 0xbb, 0x90, 0xa3, 0xfc, 0x11, 0x09, 0x64, 0x42,
	0x04, 0xe9, 0x94, 0xa0, 0x98, 0x99, 0x4a, 0xd1, 0x85, 0xda, 0x80, 0xa2, 0x38, 0x24, 0x89, 0x51,
	0x88, 0xdb, 0x1e, 0xc3, 0x98, 0xda, 0x8a, 0x71, 0xd5, 0xbf, 0xb1, 0x53, 0x4f, 0x00, 0xa9, 0xff,
	0xaa, 0xc2, 0x62, 0xac, 0xf1, 0x11, 0x7b, 0x62, 0xeb, 0x1b, 0x20, 0x57, 0xa7, 0x23, 0x8f, 0xe1,
	0xcb, 0xdc, 0x05, 0xdf, 0xdc, 0x54, 0x7c, 0xbb, 0x90, 0xe5, 0xb4, 0x24, 0xa3, 0xd5, 0x09, 0xf3,
	0x00, 0x0b, 0x2f, 0x74, 0x04, 0x8b, 0xa2, 0x42, 0x45, 0xcb, 0x91, 0xc4, 0xf9, 0x24, 0x28, 0xec,
	0x57, 0x64, 0x9c, 0xc4, 0x00, 0xc0, 0x65, 0x6f, 0xdc, 0xa4, 0xff, 0xa6, 0xc2, 0x62, 0xbc, 0x4f,
	0x12, 0x7b, 0x52, 0xab, 0x9e, 0xf1, 0x15, 0x1a, 0xf0, 0xcd, 0xdc, 0x82, 0xef, 0xec, 0xc0, 0x9e,
	0xc3, 0xc2, 0xe8, 0xcd, 0x48, 0x92, 0xdb, 0x4c, 0x21, 0xc7, 0xfc, 0x9e, 0x4b, 0x37, 0x5c, 0xf2,
	0xe2, 0x4b, 0x46, 0x52, 0x24, 0x1c, 0xa1, 0x14, 0x49, 0x8f, 0x92, 0x4c, 0x4c, 0x32, 0x5c, 0xa6,
	0xe3, 0x26, 0xfd, 0x87, 0x04, 0xc9, 0x49, 0x33, 0xe7, 0xde, 0x8b, 0xf1, 0x10, 0x4a, 0x23, 0xf7,
	0x41, 0xc9, 0xf3, 0xdd, 0x24, 0x1b, 0x96, 0xe2, 0x00, 0x4d, 0xd1, 0x89, 0xad, 0x92, 0x64, 0xd8,
	0x6e, 0x54, 0xc4, 0x69, 0x64, 0xb8, 0xdc, 0x51, 0x32, 0xdc, 0xa4, 0x7f, 0xa7, 0x02, 0x1a, 0xce,
	0x24, 0x39, 0x1b, 0xed, 0x7f, 0x5b, 0x93, 0xb3, 0x63, 0xf9, 0x08, 0x0a, 0xb1, 0xb9, 0x26, 0xa1,
	0x6c, 0x4c, 0x78, 0x61, 0x44, 0xbd, 0xc1, 0x70, 0xe0, 0x31, 0x20, 0x72, 0xc0, 0x9a, 0xf1, 0x63,
	0x46, 0x81, 0x24, 0x26, 0x3f, 0x2e, 0x27, 0xa6, 0xb2, 0xfe, 0x93, 0x0a, 0xcb, 0xc3, 0xe5, 0x70,
	0x70, 0xff, 0xff, 0x98, 0x7c, 0x01, 0x2b, 0xf6, 0x20, 0xfd, 0x14, 0x2c, 0xeb, 0x32, 0x74, 0xda,
	0xe5, 0x04, 0x2f, 0xd9, 0x29, 0x56, 0xfd, 0x67, 0x15, 0x80, 0x5f, 0x2a, 0x88, 0x9d, 0x7e, 0xad,
	0xb8, 0xf7, 0xf2, 0x79, 0x1f, 0xf2, 0x5d, 0x96, 0x80, 0xe9, 0x85, 0x54, 0x12, 0x79, 0x28, 0xdd,
	0xa3, 0xdb, 0x0e, 0x9e, 0xef, 0x46, 0xf7, 0x9e, 0x19, 0x5b, 0xf7, 0x27, 0x50, 0x8c, 0x61, 0x0a,
	0x2a, 0xb9, 0x5a, 0x66, 0x2a, 0xf1, 0xc2, 0x90, 0x78, 0xa0, 0xff, 0xa9, 0x40, 0x69, 0x5a, 0x21,
	0xdd, 0x3b, 0xa2, 0x71, 0x15, 0x73, 0x33, 0xaa, 0x98, 0x91, 0x9a, 0xfe, 0xb7, 0x02, 0xda, 0x2d,
	0x8a, 0xe5, 0x6d, 0xd3, 0xfd, 0xf4, 0x2f, 0x05, 0x2a, 0xe2, 0x9b, 0x20, 0xf1, 0xaf, 0x9d, 0x2e,
	0x39, 0xf4, 0x5c, 0xd7, 0xea, 0xdb, 0x1d, 0xef, 0xca, 0xe9, 0xa2, 0x2d, 0xd8, 0xc4, 0x46, 0x07,
	0x37, 0x8d, 0x97, 0x86, 0xd9, 0x7a, 0x75, 0x6c, 0xe0, 0xb6, 0xd9, 0xc2, 0x0d, 0x03, 0x9b, 0x47,
	0xcd, 0x76, 0xa7, 0x85, 0x9b, 0x46, 0x5b, 0x7b, 0x80, 0xb6, 0xa1, 0x36, 0x70, 0xea, 0x18, 0xc7,
	0x07, 0xc7, 0x9d, 0xa4, 0x97, 0x82, 0x56, 0x61, 0x91, 0x9f, 0x60, 0x62, 0xe3, 0x65, 0xd3, 0x78,
	0x25, 0x3d, 0x35, 0x95, 0x6d, 0x88, 0xff, 0xa3, 0x1d, 0xee, 0xa6, 0x65, 0x92, 0x1b, 0xcd, 0x8e,
	0xf1, 0x79, 0x5b, 0x9b, 0x63, 0x1b, 0x07, 0x2f, 0x5e, 0xe0, 0x56, 0x94, 0x94, 0x88, 0xa6, 0x65,
	0xd1, 0x1a, 0xac, 0x34, 0x9a, 0xed, 0xb4, 0xbd, 0x1c, 0x2a, 0x41, 0xfe, 0xf0, 0xc8, 0x38, 0xfc,
	0xcc, 0x6c, 0x9d, 0x74, 0xb4, 0x77, 0x9e, 0xfe, 0xa2, 0xc2, 0x4a, 0x5c, 0xb6, 0xc1, 0x3e, 0x02,
	0x21, 0x7a, 0x1b, 0x6a, 0xe9, 0x5a, 0xcd, 0x48, 0x66, 0x43, 0x7b, 0x80, 0x9e, 0xc0, 0xe3, 0x09,
	0x62, 0x63, 0x6e, 0x0a, 0x7a, 0x04, 0xcb, 0x71, 0xd9, 0x46, 0x63, 0x28, 0xfc, 0x11, 0x2c, 0x8f,
	0xe8, 0x33, 0x1a, 0x03, 0xe9, 0x29, 0x5b, 0x91, 0xf8, 0x0a, 0x2c, 0xc5, 0x84, 0x99, 0x52, 0x6c,
	0x43, 0xcb, 0xa2, 0x75, 0x58, 0x8d, 0xef, 0x0c, 0x49, 0x34, 0xb4, 0x1c, 0x7a, 0x08, 0x05, 0x2e,
	0x9f, 0x05, 0x61, 0x00, 0x10, 0x82, 0x85, 0xb1, 0x13, 0xe6, 0xd1, 0x32, 0x94, 0x93, 0xcf, 0xe6,
	0x3f, 0x7d, 0xf6, 0xe5, 0xc7, 0xe7, 0x0e, 0xed, 0x85, 0xa7, 0xf5, 0xae, 0xe7, 0xee, 0x39, 0x97,
	0x3d, 0xcb, 0x75, 0x7b, 0xb6, 0xbd, 0x27, 0xbe, 0x66, 0xed, 0xb2, 0x1b, 0x33, 0x39, 0xf3, 0xbd,
	0x3e, 0xdd, 0x0d, 0x04, 0xcc, 0xbd, 0x30, 0x20, 0x5d, 0x2b, 0x20, 0xc1, 0x9e, 0xf8, 0x75, 0xea,
	0x34, 0xc7, 0x7f, 0x0a, 0xfa, 0xf0, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x64, 0x3e, 0x86,
	0xe7, 0x12, 0x00, 0x00,
}
