// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/store.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	store "github.com/ilhammhdd/kudaki-storefront-service/entities/aggregates/store"
	user "github.com/ilhammhdd/kudaki-storefront-service/entities/aggregates/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//storefront service commands
type StorefrontServiceCommandTopic int32

const (
	StorefrontServiceCommandTopic_ADD_STOREFRONT_ITEM       StorefrontServiceCommandTopic = 0
	StorefrontServiceCommandTopic_DELETE_STOREFRONT_ITEM    StorefrontServiceCommandTopic = 1
	StorefrontServiceCommandTopic_UPDATE_STOREFRONT_ITEM    StorefrontServiceCommandTopic = 2
	StorefrontServiceCommandTopic_RETRIEVE_STOREFRONT_ITEMS StorefrontServiceCommandTopic = 3
)

var StorefrontServiceCommandTopic_name = map[int32]string{
	0: "ADD_STOREFRONT_ITEM",
	1: "DELETE_STOREFRONT_ITEM",
	2: "UPDATE_STOREFRONT_ITEM",
	3: "RETRIEVE_STOREFRONT_ITEMS",
}

var StorefrontServiceCommandTopic_value = map[string]int32{
	"ADD_STOREFRONT_ITEM":       0,
	"DELETE_STOREFRONT_ITEM":    1,
	"UPDATE_STOREFRONT_ITEM":    2,
	"RETRIEVE_STOREFRONT_ITEMS": 3,
}

func (x StorefrontServiceCommandTopic) String() string {
	return proto.EnumName(StorefrontServiceCommandTopic_name, int32(x))
}

func (StorefrontServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{0}
}

//
//storefront service events
type StorefrontServiceEventTopic int32

const (
	StorefrontServiceEventTopic_STOREFRONT_ITEM_ADDED      StorefrontServiceEventTopic = 0
	StorefrontServiceEventTopic_STOREFRONT_ITEM_DELETED    StorefrontServiceEventTopic = 1
	StorefrontServiceEventTopic_STOREFRONT_ITEMS_UPDATED   StorefrontServiceEventTopic = 2
	StorefrontServiceEventTopic_STOREFRONT_ITEMS_RETRIEVED StorefrontServiceEventTopic = 3
)

var StorefrontServiceEventTopic_name = map[int32]string{
	0: "STOREFRONT_ITEM_ADDED",
	1: "STOREFRONT_ITEM_DELETED",
	2: "STOREFRONT_ITEMS_UPDATED",
	3: "STOREFRONT_ITEMS_RETRIEVED",
}

var StorefrontServiceEventTopic_value = map[string]int32{
	"STOREFRONT_ITEM_ADDED":      0,
	"STOREFRONT_ITEM_DELETED":    1,
	"STOREFRONT_ITEMS_UPDATED":   2,
	"STOREFRONT_ITEMS_RETRIEVED": 3,
}

func (x StorefrontServiceEventTopic) String() string {
	return proto.EnumName(StorefrontServiceEventTopic_name, int32(x))
}

func (StorefrontServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{1}
}

//
//item service commands
type ItemServiceCommandTopic int32

const (
	ItemServiceCommandTopic_RETRIEVE_ITEMS ItemServiceCommandTopic = 0
	ItemServiceCommandTopic_SEARCH_ITEMS   ItemServiceCommandTopic = 1
)

var ItemServiceCommandTopic_name = map[int32]string{
	0: "RETRIEVE_ITEMS",
	1: "SEARCH_ITEMS",
}

var ItemServiceCommandTopic_value = map[string]int32{
	"RETRIEVE_ITEMS": 0,
	"SEARCH_ITEMS":   1,
}

func (x ItemServiceCommandTopic) String() string {
	return proto.EnumName(ItemServiceCommandTopic_name, int32(x))
}

func (ItemServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{2}
}

//
//item service events
type ItemServiceEventTopic int32

const (
	ItemServiceEventTopic_ITEMS_RETRIEVED ItemServiceEventTopic = 0
	ItemServiceEventTopic_ITEMS_SEARCHED  ItemServiceEventTopic = 1
)

var ItemServiceEventTopic_name = map[int32]string{
	0: "ITEMS_RETRIEVED",
	1: "ITEMS_SEARCHED",
}

var ItemServiceEventTopic_value = map[string]int32{
	"ITEMS_RETRIEVED": 0,
	"ITEMS_SEARCHED":  1,
}

func (x ItemServiceEventTopic) String() string {
	return proto.EnumName(ItemServiceEventTopic_name, int32(x))
}

func (ItemServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{3}
}

//
//item review service commands
type ItemReviewServiceCommandTopic int32

const (
	ItemReviewServiceCommandTopic_REVIEW_ITEM                   ItemReviewServiceCommandTopic = 0
	ItemReviewServiceCommandTopic_RETRIEVE_ITEM_REVIEWS         ItemReviewServiceCommandTopic = 1
	ItemReviewServiceCommandTopic_COMMENT_ITEM_REVIEW           ItemReviewServiceCommandTopic = 2
	ItemReviewServiceCommandTopic_RETRIEVE_ITEM_REVIEW_COMMENTS ItemReviewServiceCommandTopic = 3
)

var ItemReviewServiceCommandTopic_name = map[int32]string{
	0: "REVIEW_ITEM",
	1: "RETRIEVE_ITEM_REVIEWS",
	2: "COMMENT_ITEM_REVIEW",
	3: "RETRIEVE_ITEM_REVIEW_COMMENTS",
}

var ItemReviewServiceCommandTopic_value = map[string]int32{
	"REVIEW_ITEM":                   0,
	"RETRIEVE_ITEM_REVIEWS":         1,
	"COMMENT_ITEM_REVIEW":           2,
	"RETRIEVE_ITEM_REVIEW_COMMENTS": 3,
}

func (x ItemReviewServiceCommandTopic) String() string {
	return proto.EnumName(ItemReviewServiceCommandTopic_name, int32(x))
}

func (ItemReviewServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{4}
}

//
//item review service events
type ItemReviewServiceEventTopic int32

const (
	ItemReviewServiceEventTopic_ITEM_REVIEWED                  ItemReviewServiceEventTopic = 0
	ItemReviewServiceEventTopic_ITEM_REVIEWS_RETRIEVED         ItemReviewServiceEventTopic = 1
	ItemReviewServiceEventTopic_ITEM_REVIEW_COMMENTED          ItemReviewServiceEventTopic = 2
	ItemReviewServiceEventTopic_ITEM_REVIEW_COMMENTS_RETRIEVED ItemReviewServiceEventTopic = 3
)

var ItemReviewServiceEventTopic_name = map[int32]string{
	0: "ITEM_REVIEWED",
	1: "ITEM_REVIEWS_RETRIEVED",
	2: "ITEM_REVIEW_COMMENTED",
	3: "ITEM_REVIEW_COMMENTS_RETRIEVED",
}

var ItemReviewServiceEventTopic_value = map[string]int32{
	"ITEM_REVIEWED":                  0,
	"ITEM_REVIEWS_RETRIEVED":         1,
	"ITEM_REVIEW_COMMENTED":          2,
	"ITEM_REVIEW_COMMENTS_RETRIEVED": 3,
}

func (x ItemReviewServiceEventTopic) String() string {
	return proto.EnumName(ItemReviewServiceEventTopic_name, int32(x))
}

func (ItemReviewServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{5}
}

type AddStorefrontItem struct {
	Uid                  string                  `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string                  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int32                   `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Unit                 string                  `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Price                int32                   `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Description          string                  `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Photo                string                  `protobuf:"bytes,9,opt,name=photo,proto3" json:"photo,omitempty"`
	KudakiToken          string                  `protobuf:"bytes,10,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	PriceDuration        store.PriceDuration     `protobuf:"varint,11,opt,name=price_duration,json=priceDuration,proto3,enum=aggregates.store.PriceDuration" json:"price_duration,omitempty"`
	Length               int32                   `protobuf:"varint,12,opt,name=length,proto3" json:"length,omitempty"`
	Width                int32                   `protobuf:"varint,13,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32                   `protobuf:"varint,14,opt,name=height,proto3" json:"height,omitempty"`
	UnitOfMeasurement    store.UnitofMeasurement `protobuf:"varint,15,opt,name=unit_of_measurement,json=unitOfMeasurement,proto3,enum=aggregates.store.UnitofMeasurement" json:"unit_of_measurement,omitempty"`
	Color                string                  `protobuf:"bytes,16,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AddStorefrontItem) Reset()         { *m = AddStorefrontItem{} }
func (m *AddStorefrontItem) String() string { return proto.CompactTextString(m) }
func (*AddStorefrontItem) ProtoMessage()    {}
func (*AddStorefrontItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{0}
}

func (m *AddStorefrontItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStorefrontItem.Unmarshal(m, b)
}
func (m *AddStorefrontItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStorefrontItem.Marshal(b, m, deterministic)
}
func (m *AddStorefrontItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStorefrontItem.Merge(m, src)
}
func (m *AddStorefrontItem) XXX_Size() int {
	return xxx_messageInfo_AddStorefrontItem.Size(m)
}
func (m *AddStorefrontItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStorefrontItem.DiscardUnknown(m)
}

var xxx_messageInfo_AddStorefrontItem proto.InternalMessageInfo

func (m *AddStorefrontItem) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddStorefrontItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddStorefrontItem) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AddStorefrontItem) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *AddStorefrontItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddStorefrontItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddStorefrontItem) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *AddStorefrontItem) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *AddStorefrontItem) GetPriceDuration() store.PriceDuration {
	if m != nil {
		return m.PriceDuration
	}
	return store.PriceDuration_DAY
}

func (m *AddStorefrontItem) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *AddStorefrontItem) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *AddStorefrontItem) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AddStorefrontItem) GetUnitOfMeasurement() store.UnitofMeasurement {
	if m != nil {
		return m.UnitOfMeasurement
	}
	return store.UnitofMeasurement_MM
}

func (m *AddStorefrontItem) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type DeleteStorefrontItem struct {
	Uid      string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ItemUuid string `protobuf:"bytes,2,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	// string storefront_uuid = 3;
	KudakiToken          string   `protobuf:"bytes,4,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorefrontItem) Reset()         { *m = DeleteStorefrontItem{} }
func (m *DeleteStorefrontItem) String() string { return proto.CompactTextString(m) }
func (*DeleteStorefrontItem) ProtoMessage()    {}
func (*DeleteStorefrontItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{1}
}

func (m *DeleteStorefrontItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorefrontItem.Unmarshal(m, b)
}
func (m *DeleteStorefrontItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorefrontItem.Marshal(b, m, deterministic)
}
func (m *DeleteStorefrontItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorefrontItem.Merge(m, src)
}
func (m *DeleteStorefrontItem) XXX_Size() int {
	return xxx_messageInfo_DeleteStorefrontItem.Size(m)
}
func (m *DeleteStorefrontItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorefrontItem.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorefrontItem proto.InternalMessageInfo

func (m *DeleteStorefrontItem) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DeleteStorefrontItem) GetItemUuid() string {
	if m != nil {
		return m.ItemUuid
	}
	return ""
}

func (m *DeleteStorefrontItem) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

type UpdateStorefrontItem struct {
	Uid                  string                  `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string                  `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	ItemUuid             string                  `protobuf:"bytes,3,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	Name                 string                  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int32                   `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Unit                 string                  `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Price                int32                   `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Description          string                  `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Photo                string                  `protobuf:"bytes,9,opt,name=photo,proto3" json:"photo,omitempty"`
	PriceDuration        store.PriceDuration     `protobuf:"varint,10,opt,name=price_duration,json=priceDuration,proto3,enum=aggregates.store.PriceDuration" json:"price_duration,omitempty"`
	Length               int32                   `protobuf:"varint,11,opt,name=length,proto3" json:"length,omitempty"`
	Width                int32                   `protobuf:"varint,12,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32                   `protobuf:"varint,13,opt,name=height,proto3" json:"height,omitempty"`
	UnitOfMeasurement    store.UnitofMeasurement `protobuf:"varint,14,opt,name=unit_of_measurement,json=unitOfMeasurement,proto3,enum=aggregates.store.UnitofMeasurement" json:"unit_of_measurement,omitempty"`
	Color                string                  `protobuf:"bytes,15,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateStorefrontItem) Reset()         { *m = UpdateStorefrontItem{} }
func (m *UpdateStorefrontItem) String() string { return proto.CompactTextString(m) }
func (*UpdateStorefrontItem) ProtoMessage()    {}
func (*UpdateStorefrontItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{2}
}

func (m *UpdateStorefrontItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStorefrontItem.Unmarshal(m, b)
}
func (m *UpdateStorefrontItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStorefrontItem.Marshal(b, m, deterministic)
}
func (m *UpdateStorefrontItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStorefrontItem.Merge(m, src)
}
func (m *UpdateStorefrontItem) XXX_Size() int {
	return xxx_messageInfo_UpdateStorefrontItem.Size(m)
}
func (m *UpdateStorefrontItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStorefrontItem.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStorefrontItem proto.InternalMessageInfo

func (m *UpdateStorefrontItem) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateStorefrontItem) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *UpdateStorefrontItem) GetItemUuid() string {
	if m != nil {
		return m.ItemUuid
	}
	return ""
}

func (m *UpdateStorefrontItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateStorefrontItem) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UpdateStorefrontItem) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *UpdateStorefrontItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdateStorefrontItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateStorefrontItem) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *UpdateStorefrontItem) GetPriceDuration() store.PriceDuration {
	if m != nil {
		return m.PriceDuration
	}
	return store.PriceDuration_DAY
}

func (m *UpdateStorefrontItem) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *UpdateStorefrontItem) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *UpdateStorefrontItem) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *UpdateStorefrontItem) GetUnitOfMeasurement() store.UnitofMeasurement {
	if m != nil {
		return m.UnitOfMeasurement
	}
	return store.UnitofMeasurement_MM
}

func (m *UpdateStorefrontItem) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type RetrieveStorefrontItems struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	StorefrontUuid       string   `protobuf:"bytes,3,opt,name=storefront_uuid,json=storefrontUuid,proto3" json:"storefront_uuid,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	ResultSchema         []byte   `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveStorefrontItems) Reset()         { *m = RetrieveStorefrontItems{} }
func (m *RetrieveStorefrontItems) String() string { return proto.CompactTextString(m) }
func (*RetrieveStorefrontItems) ProtoMessage()    {}
func (*RetrieveStorefrontItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{3}
}

func (m *RetrieveStorefrontItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveStorefrontItems.Unmarshal(m, b)
}
func (m *RetrieveStorefrontItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveStorefrontItems.Marshal(b, m, deterministic)
}
func (m *RetrieveStorefrontItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveStorefrontItems.Merge(m, src)
}
func (m *RetrieveStorefrontItems) XXX_Size() int {
	return xxx_messageInfo_RetrieveStorefrontItems.Size(m)
}
func (m *RetrieveStorefrontItems) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveStorefrontItems.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveStorefrontItems proto.InternalMessageInfo

func (m *RetrieveStorefrontItems) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveStorefrontItems) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveStorefrontItems) GetStorefrontUuid() string {
	if m != nil {
		return m.StorefrontUuid
	}
	return ""
}

func (m *RetrieveStorefrontItems) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveStorefrontItems) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveStorefrontItems) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type StorefrontItemAdded struct {
	Uid                  string             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Item                 *store.Item        `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	EventStatus          *Status            `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	AddStorefrontItem    *AddStorefrontItem `protobuf:"bytes,4,opt,name=add_storefront_item,json=addStorefrontItem,proto3" json:"add_storefront_item,omitempty"`
	Requester            *user.User         `protobuf:"bytes,5,opt,name=requester,proto3" json:"requester,omitempty"`
	Storefront           *store.Storefront  `protobuf:"bytes,6,opt,name=storefront,proto3" json:"storefront,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StorefrontItemAdded) Reset()         { *m = StorefrontItemAdded{} }
func (m *StorefrontItemAdded) String() string { return proto.CompactTextString(m) }
func (*StorefrontItemAdded) ProtoMessage()    {}
func (*StorefrontItemAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{4}
}

func (m *StorefrontItemAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontItemAdded.Unmarshal(m, b)
}
func (m *StorefrontItemAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontItemAdded.Marshal(b, m, deterministic)
}
func (m *StorefrontItemAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontItemAdded.Merge(m, src)
}
func (m *StorefrontItemAdded) XXX_Size() int {
	return xxx_messageInfo_StorefrontItemAdded.Size(m)
}
func (m *StorefrontItemAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontItemAdded.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontItemAdded proto.InternalMessageInfo

func (m *StorefrontItemAdded) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StorefrontItemAdded) GetItem() *store.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *StorefrontItemAdded) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *StorefrontItemAdded) GetAddStorefrontItem() *AddStorefrontItem {
	if m != nil {
		return m.AddStorefrontItem
	}
	return nil
}

func (m *StorefrontItemAdded) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *StorefrontItemAdded) GetStorefront() *store.Storefront {
	if m != nil {
		return m.Storefront
	}
	return nil
}

type StorefrontItemDeleted struct {
	Uid                  string                `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Item                 *store.Item           `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	EventStatus          *Status               `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Requester            *user.User            `protobuf:"bytes,4,opt,name=requester,proto3" json:"requester,omitempty"`
	DeleteStorefrontItem *DeleteStorefrontItem `protobuf:"bytes,5,opt,name=delete_storefront_item,json=deleteStorefrontItem,proto3" json:"delete_storefront_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StorefrontItemDeleted) Reset()         { *m = StorefrontItemDeleted{} }
func (m *StorefrontItemDeleted) String() string { return proto.CompactTextString(m) }
func (*StorefrontItemDeleted) ProtoMessage()    {}
func (*StorefrontItemDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{5}
}

func (m *StorefrontItemDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontItemDeleted.Unmarshal(m, b)
}
func (m *StorefrontItemDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontItemDeleted.Marshal(b, m, deterministic)
}
func (m *StorefrontItemDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontItemDeleted.Merge(m, src)
}
func (m *StorefrontItemDeleted) XXX_Size() int {
	return xxx_messageInfo_StorefrontItemDeleted.Size(m)
}
func (m *StorefrontItemDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontItemDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontItemDeleted proto.InternalMessageInfo

func (m *StorefrontItemDeleted) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StorefrontItemDeleted) GetItem() *store.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *StorefrontItemDeleted) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *StorefrontItemDeleted) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *StorefrontItemDeleted) GetDeleteStorefrontItem() *DeleteStorefrontItem {
	if m != nil {
		return m.DeleteStorefrontItem
	}
	return nil
}

type StorefrontItemsUpdated struct {
	Uid                  string                `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ItemsBefore          []*store.Item         `protobuf:"bytes,2,rep,name=items_before,json=itemsBefore,proto3" json:"items_before,omitempty"`
	ItemsAfter           []*store.Item         `protobuf:"bytes,3,rep,name=items_after,json=itemsAfter,proto3" json:"items_after,omitempty"`
	EventStatus          *Status               `protobuf:"bytes,4,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Requester            *user.User            `protobuf:"bytes,5,opt,name=requester,proto3" json:"requester,omitempty"`
	UpdateStorefrontItem *UpdateStorefrontItem `protobuf:"bytes,6,opt,name=update_storefront_item,json=updateStorefrontItem,proto3" json:"update_storefront_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StorefrontItemsUpdated) Reset()         { *m = StorefrontItemsUpdated{} }
func (m *StorefrontItemsUpdated) String() string { return proto.CompactTextString(m) }
func (*StorefrontItemsUpdated) ProtoMessage()    {}
func (*StorefrontItemsUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{6}
}

func (m *StorefrontItemsUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontItemsUpdated.Unmarshal(m, b)
}
func (m *StorefrontItemsUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontItemsUpdated.Marshal(b, m, deterministic)
}
func (m *StorefrontItemsUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontItemsUpdated.Merge(m, src)
}
func (m *StorefrontItemsUpdated) XXX_Size() int {
	return xxx_messageInfo_StorefrontItemsUpdated.Size(m)
}
func (m *StorefrontItemsUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontItemsUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontItemsUpdated proto.InternalMessageInfo

func (m *StorefrontItemsUpdated) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StorefrontItemsUpdated) GetItemsBefore() []*store.Item {
	if m != nil {
		return m.ItemsBefore
	}
	return nil
}

func (m *StorefrontItemsUpdated) GetItemsAfter() []*store.Item {
	if m != nil {
		return m.ItemsAfter
	}
	return nil
}

func (m *StorefrontItemsUpdated) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *StorefrontItemsUpdated) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *StorefrontItemsUpdated) GetUpdateStorefrontItem() *UpdateStorefrontItem {
	if m != nil {
		return m.UpdateStorefrontItem
	}
	return nil
}

type StorefrontItemsRetrieved struct {
	Uid                     string                   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Requester               *user.User               `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	EventStatus             *Status                  `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RetrieveStorefrontItems *RetrieveStorefrontItems `protobuf:"bytes,4,opt,name=retrieve_storefront_items,json=retrieveStorefrontItems,proto3" json:"retrieve_storefront_items,omitempty"`
	Result                  []byte                   `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *StorefrontItemsRetrieved) Reset()         { *m = StorefrontItemsRetrieved{} }
func (m *StorefrontItemsRetrieved) String() string { return proto.CompactTextString(m) }
func (*StorefrontItemsRetrieved) ProtoMessage()    {}
func (*StorefrontItemsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{7}
}

func (m *StorefrontItemsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontItemsRetrieved.Unmarshal(m, b)
}
func (m *StorefrontItemsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontItemsRetrieved.Marshal(b, m, deterministic)
}
func (m *StorefrontItemsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontItemsRetrieved.Merge(m, src)
}
func (m *StorefrontItemsRetrieved) XXX_Size() int {
	return xxx_messageInfo_StorefrontItemsRetrieved.Size(m)
}
func (m *StorefrontItemsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontItemsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontItemsRetrieved proto.InternalMessageInfo

func (m *StorefrontItemsRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StorefrontItemsRetrieved) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *StorefrontItemsRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *StorefrontItemsRetrieved) GetRetrieveStorefrontItems() *RetrieveStorefrontItems {
	if m != nil {
		return m.RetrieveStorefrontItems
	}
	return nil
}

func (m *StorefrontItemsRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type RetrieveItems struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	KudakiToken          string   `protobuf:"bytes,4,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveItems) Reset()         { *m = RetrieveItems{} }
func (m *RetrieveItems) String() string { return proto.CompactTextString(m) }
func (*RetrieveItems) ProtoMessage()    {}
func (*RetrieveItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{8}
}

func (m *RetrieveItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveItems.Unmarshal(m, b)
}
func (m *RetrieveItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveItems.Marshal(b, m, deterministic)
}
func (m *RetrieveItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveItems.Merge(m, src)
}
func (m *RetrieveItems) XXX_Size() int {
	return xxx_messageInfo_RetrieveItems.Size(m)
}
func (m *RetrieveItems) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveItems.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveItems proto.InternalMessageInfo

func (m *RetrieveItems) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveItems) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveItems) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveItems) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

type SearchItems struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Keyword              string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchItems) Reset()         { *m = SearchItems{} }
func (m *SearchItems) String() string { return proto.CompactTextString(m) }
func (*SearchItems) ProtoMessage()    {}
func (*SearchItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{9}
}

func (m *SearchItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchItems.Unmarshal(m, b)
}
func (m *SearchItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchItems.Marshal(b, m, deterministic)
}
func (m *SearchItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchItems.Merge(m, src)
}
func (m *SearchItems) XXX_Size() int {
	return xxx_messageInfo_SearchItems.Size(m)
}
func (m *SearchItems) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchItems.DiscardUnknown(m)
}

var xxx_messageInfo_SearchItems proto.InternalMessageInfo

func (m *SearchItems) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SearchItems) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *SearchItems) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchItems) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchItems) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ItemsRetrieved struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Offset               int32          `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32          `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Requester            *user.User     `protobuf:"bytes,4,opt,name=requester,proto3" json:"requester,omitempty"`
	EventStatus          *Status        `protobuf:"bytes,5,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Result               []byte         `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	RetrieveItems        *RetrieveItems `protobuf:"bytes,7,opt,name=retrieve_items,json=retrieveItems,proto3" json:"retrieve_items,omitempty"`
	Items                []*store.Item  `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ItemsRetrieved) Reset()         { *m = ItemsRetrieved{} }
func (m *ItemsRetrieved) String() string { return proto.CompactTextString(m) }
func (*ItemsRetrieved) ProtoMessage()    {}
func (*ItemsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{10}
}

func (m *ItemsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsRetrieved.Unmarshal(m, b)
}
func (m *ItemsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsRetrieved.Marshal(b, m, deterministic)
}
func (m *ItemsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsRetrieved.Merge(m, src)
}
func (m *ItemsRetrieved) XXX_Size() int {
	return xxx_messageInfo_ItemsRetrieved.Size(m)
}
func (m *ItemsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsRetrieved proto.InternalMessageInfo

func (m *ItemsRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ItemsRetrieved) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ItemsRetrieved) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ItemsRetrieved) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *ItemsRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemsRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ItemsRetrieved) GetRetrieveItems() *RetrieveItems {
	if m != nil {
		return m.RetrieveItems
	}
	return nil
}

func (m *ItemsRetrieved) GetItems() []*store.Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ItemsSearched struct {
	Uid         string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Requester   *user.User `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	EventStatus *Status    `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	// repeated aggregates.store.Item items = 4;
	Result               []byte       `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	SearchItems          *SearchItems `protobuf:"bytes,5,opt,name=search_items,json=searchItems,proto3" json:"search_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ItemsSearched) Reset()         { *m = ItemsSearched{} }
func (m *ItemsSearched) String() string { return proto.CompactTextString(m) }
func (*ItemsSearched) ProtoMessage()    {}
func (*ItemsSearched) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{11}
}

func (m *ItemsSearched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsSearched.Unmarshal(m, b)
}
func (m *ItemsSearched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsSearched.Marshal(b, m, deterministic)
}
func (m *ItemsSearched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsSearched.Merge(m, src)
}
func (m *ItemsSearched) XXX_Size() int {
	return xxx_messageInfo_ItemsSearched.Size(m)
}
func (m *ItemsSearched) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsSearched.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsSearched proto.InternalMessageInfo

func (m *ItemsSearched) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ItemsSearched) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *ItemsSearched) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemsSearched) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ItemsSearched) GetSearchItems() *SearchItems {
	if m != nil {
		return m.SearchItems
	}
	return nil
}

type ReviewItem struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	ItemUuid             string   `protobuf:"bytes,4,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	Review               string   `protobuf:"bytes,5,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewItem) Reset()         { *m = ReviewItem{} }
func (m *ReviewItem) String() string { return proto.CompactTextString(m) }
func (*ReviewItem) ProtoMessage()    {}
func (*ReviewItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{12}
}

func (m *ReviewItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewItem.Unmarshal(m, b)
}
func (m *ReviewItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewItem.Marshal(b, m, deterministic)
}
func (m *ReviewItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewItem.Merge(m, src)
}
func (m *ReviewItem) XXX_Size() int {
	return xxx_messageInfo_ReviewItem.Size(m)
}
func (m *ReviewItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewItem.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewItem proto.InternalMessageInfo

func (m *ReviewItem) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReviewItem) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *ReviewItem) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *ReviewItem) GetItemUuid() string {
	if m != nil {
		return m.ItemUuid
	}
	return ""
}

func (m *ReviewItem) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type RetrieveItemReviews struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	ItemUuid             string   `protobuf:"bytes,3,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveItemReviews) Reset()         { *m = RetrieveItemReviews{} }
func (m *RetrieveItemReviews) String() string { return proto.CompactTextString(m) }
func (*RetrieveItemReviews) ProtoMessage()    {}
func (*RetrieveItemReviews) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{13}
}

func (m *RetrieveItemReviews) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveItemReviews.Unmarshal(m, b)
}
func (m *RetrieveItemReviews) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveItemReviews.Marshal(b, m, deterministic)
}
func (m *RetrieveItemReviews) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveItemReviews.Merge(m, src)
}
func (m *RetrieveItemReviews) XXX_Size() int {
	return xxx_messageInfo_RetrieveItemReviews.Size(m)
}
func (m *RetrieveItemReviews) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveItemReviews.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveItemReviews proto.InternalMessageInfo

func (m *RetrieveItemReviews) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveItemReviews) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveItemReviews) GetItemUuid() string {
	if m != nil {
		return m.ItemUuid
	}
	return ""
}

func (m *RetrieveItemReviews) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveItemReviews) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type CommentItemReview struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ItemReviewUuid       string   `protobuf:"bytes,4,opt,name=item_review_uuid,json=itemReviewUuid,proto3" json:"item_review_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentItemReview) Reset()         { *m = CommentItemReview{} }
func (m *CommentItemReview) String() string { return proto.CompactTextString(m) }
func (*CommentItemReview) ProtoMessage()    {}
func (*CommentItemReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{14}
}

func (m *CommentItemReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentItemReview.Unmarshal(m, b)
}
func (m *CommentItemReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentItemReview.Marshal(b, m, deterministic)
}
func (m *CommentItemReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentItemReview.Merge(m, src)
}
func (m *CommentItemReview) XXX_Size() int {
	return xxx_messageInfo_CommentItemReview.Size(m)
}
func (m *CommentItemReview) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentItemReview.DiscardUnknown(m)
}

var xxx_messageInfo_CommentItemReview proto.InternalMessageInfo

func (m *CommentItemReview) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CommentItemReview) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *CommentItemReview) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *CommentItemReview) GetItemReviewUuid() string {
	if m != nil {
		return m.ItemReviewUuid
	}
	return ""
}

type RetrieveItemReviewComments struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	ItemReviewUuid       string   `protobuf:"bytes,3,opt,name=item_review_uuid,json=itemReviewUuid,proto3" json:"item_review_uuid,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveItemReviewComments) Reset()         { *m = RetrieveItemReviewComments{} }
func (m *RetrieveItemReviewComments) String() string { return proto.CompactTextString(m) }
func (*RetrieveItemReviewComments) ProtoMessage()    {}
func (*RetrieveItemReviewComments) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{15}
}

func (m *RetrieveItemReviewComments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveItemReviewComments.Unmarshal(m, b)
}
func (m *RetrieveItemReviewComments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveItemReviewComments.Marshal(b, m, deterministic)
}
func (m *RetrieveItemReviewComments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveItemReviewComments.Merge(m, src)
}
func (m *RetrieveItemReviewComments) XXX_Size() int {
	return xxx_messageInfo_RetrieveItemReviewComments.Size(m)
}
func (m *RetrieveItemReviewComments) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveItemReviewComments.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveItemReviewComments proto.InternalMessageInfo

func (m *RetrieveItemReviewComments) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveItemReviewComments) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveItemReviewComments) GetItemReviewUuid() string {
	if m != nil {
		return m.ItemReviewUuid
	}
	return ""
}

func (m *RetrieveItemReviewComments) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveItemReviewComments) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ItemReviewed struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Requester            *user.User        `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	EventStatus          *Status           `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	ItemReview           *store.ItemReview `protobuf:"bytes,4,opt,name=item_review,json=itemReview,proto3" json:"item_review,omitempty"`
	ReviewItem           *ReviewItem       `protobuf:"bytes,5,opt,name=review_item,json=reviewItem,proto3" json:"review_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ItemReviewed) Reset()         { *m = ItemReviewed{} }
func (m *ItemReviewed) String() string { return proto.CompactTextString(m) }
func (*ItemReviewed) ProtoMessage()    {}
func (*ItemReviewed) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{16}
}

func (m *ItemReviewed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemReviewed.Unmarshal(m, b)
}
func (m *ItemReviewed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemReviewed.Marshal(b, m, deterministic)
}
func (m *ItemReviewed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemReviewed.Merge(m, src)
}
func (m *ItemReviewed) XXX_Size() int {
	return xxx_messageInfo_ItemReviewed.Size(m)
}
func (m *ItemReviewed) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemReviewed.DiscardUnknown(m)
}

var xxx_messageInfo_ItemReviewed proto.InternalMessageInfo

func (m *ItemReviewed) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ItemReviewed) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *ItemReviewed) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemReviewed) GetItemReview() *store.ItemReview {
	if m != nil {
		return m.ItemReview
	}
	return nil
}

func (m *ItemReviewed) GetReviewItem() *ReviewItem {
	if m != nil {
		return m.ReviewItem
	}
	return nil
}

type ItemReviewsRetrieved struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Requester            *user.User           `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	EventStatus          *Status              `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Result               []byte               `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	RetrieveItemReviews  *RetrieveItemReviews `protobuf:"bytes,5,opt,name=retrieve_item_reviews,json=retrieveItemReviews,proto3" json:"retrieve_item_reviews,omitempty"`
	ItemReviews          []*store.ItemReview  `protobuf:"bytes,6,rep,name=item_reviews,json=itemReviews,proto3" json:"item_reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemReviewsRetrieved) Reset()         { *m = ItemReviewsRetrieved{} }
func (m *ItemReviewsRetrieved) String() string { return proto.CompactTextString(m) }
func (*ItemReviewsRetrieved) ProtoMessage()    {}
func (*ItemReviewsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{17}
}

func (m *ItemReviewsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemReviewsRetrieved.Unmarshal(m, b)
}
func (m *ItemReviewsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemReviewsRetrieved.Marshal(b, m, deterministic)
}
func (m *ItemReviewsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemReviewsRetrieved.Merge(m, src)
}
func (m *ItemReviewsRetrieved) XXX_Size() int {
	return xxx_messageInfo_ItemReviewsRetrieved.Size(m)
}
func (m *ItemReviewsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemReviewsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_ItemReviewsRetrieved proto.InternalMessageInfo

func (m *ItemReviewsRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ItemReviewsRetrieved) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *ItemReviewsRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemReviewsRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ItemReviewsRetrieved) GetRetrieveItemReviews() *RetrieveItemReviews {
	if m != nil {
		return m.RetrieveItemReviews
	}
	return nil
}

func (m *ItemReviewsRetrieved) GetItemReviews() []*store.ItemReview {
	if m != nil {
		return m.ItemReviews
	}
	return nil
}

type ItemReviewCommented struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Requester            *user.User           `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	EventStatus          *Status              `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	ReviewComment        *store.ReviewComment `protobuf:"bytes,4,opt,name=review_comment,json=reviewComment,proto3" json:"review_comment,omitempty"`
	CommentItemReview    *CommentItemReview   `protobuf:"bytes,5,opt,name=comment_item_review,json=commentItemReview,proto3" json:"comment_item_review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemReviewCommented) Reset()         { *m = ItemReviewCommented{} }
func (m *ItemReviewCommented) String() string { return proto.CompactTextString(m) }
func (*ItemReviewCommented) ProtoMessage()    {}
func (*ItemReviewCommented) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{18}
}

func (m *ItemReviewCommented) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemReviewCommented.Unmarshal(m, b)
}
func (m *ItemReviewCommented) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemReviewCommented.Marshal(b, m, deterministic)
}
func (m *ItemReviewCommented) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemReviewCommented.Merge(m, src)
}
func (m *ItemReviewCommented) XXX_Size() int {
	return xxx_messageInfo_ItemReviewCommented.Size(m)
}
func (m *ItemReviewCommented) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemReviewCommented.DiscardUnknown(m)
}

var xxx_messageInfo_ItemReviewCommented proto.InternalMessageInfo

func (m *ItemReviewCommented) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ItemReviewCommented) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *ItemReviewCommented) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemReviewCommented) GetReviewComment() *store.ReviewComment {
	if m != nil {
		return m.ReviewComment
	}
	return nil
}

func (m *ItemReviewCommented) GetCommentItemReview() *CommentItemReview {
	if m != nil {
		return m.CommentItemReview
	}
	return nil
}

type ItemReviewCommentsRetrieved struct {
	Uid                        string                      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Requester                  *user.User                  `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	EventStatus                *Status                     `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	ReviewComments             []*store.ReviewComment      `protobuf:"bytes,4,rep,name=review_comments,json=reviewComments,proto3" json:"review_comments,omitempty"`
	RetrieveItemReviewComments *RetrieveItemReviewComments `protobuf:"bytes,5,opt,name=retrieve_item_review_comments,json=retrieveItemReviewComments,proto3" json:"retrieve_item_review_comments,omitempty"`
	Result                     []byte                      `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *ItemReviewCommentsRetrieved) Reset()         { *m = ItemReviewCommentsRetrieved{} }
func (m *ItemReviewCommentsRetrieved) String() string { return proto.CompactTextString(m) }
func (*ItemReviewCommentsRetrieved) ProtoMessage()    {}
func (*ItemReviewCommentsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f52bba9433e5948, []int{19}
}

func (m *ItemReviewCommentsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemReviewCommentsRetrieved.Unmarshal(m, b)
}
func (m *ItemReviewCommentsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemReviewCommentsRetrieved.Marshal(b, m, deterministic)
}
func (m *ItemReviewCommentsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemReviewCommentsRetrieved.Merge(m, src)
}
func (m *ItemReviewCommentsRetrieved) XXX_Size() int {
	return xxx_messageInfo_ItemReviewCommentsRetrieved.Size(m)
}
func (m *ItemReviewCommentsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemReviewCommentsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_ItemReviewCommentsRetrieved proto.InternalMessageInfo

func (m *ItemReviewCommentsRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ItemReviewCommentsRetrieved) GetRequester() *user.User {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *ItemReviewCommentsRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemReviewCommentsRetrieved) GetReviewComments() []*store.ReviewComment {
	if m != nil {
		return m.ReviewComments
	}
	return nil
}

func (m *ItemReviewCommentsRetrieved) GetRetrieveItemReviewComments() *RetrieveItemReviewComments {
	if m != nil {
		return m.RetrieveItemReviewComments
	}
	return nil
}

func (m *ItemReviewCommentsRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterEnum("event.StorefrontServiceCommandTopic", StorefrontServiceCommandTopic_name, StorefrontServiceCommandTopic_value)
	proto.RegisterEnum("event.StorefrontServiceEventTopic", StorefrontServiceEventTopic_name, StorefrontServiceEventTopic_value)
	proto.RegisterEnum("event.ItemServiceCommandTopic", ItemServiceCommandTopic_name, ItemServiceCommandTopic_value)
	proto.RegisterEnum("event.ItemServiceEventTopic", ItemServiceEventTopic_name, ItemServiceEventTopic_value)
	proto.RegisterEnum("event.ItemReviewServiceCommandTopic", ItemReviewServiceCommandTopic_name, ItemReviewServiceCommandTopic_value)
	proto.RegisterEnum("event.ItemReviewServiceEventTopic", ItemReviewServiceEventTopic_name, ItemReviewServiceEventTopic_value)
	proto.RegisterType((*AddStorefrontItem)(nil), "event.AddStorefrontItem")
	proto.RegisterType((*DeleteStorefrontItem)(nil), "event.DeleteStorefrontItem")
	proto.RegisterType((*UpdateStorefrontItem)(nil), "event.UpdateStorefrontItem")
	proto.RegisterType((*RetrieveStorefrontItems)(nil), "event.RetrieveStorefrontItems")
	proto.RegisterType((*StorefrontItemAdded)(nil), "event.StorefrontItemAdded")
	proto.RegisterType((*StorefrontItemDeleted)(nil), "event.StorefrontItemDeleted")
	proto.RegisterType((*StorefrontItemsUpdated)(nil), "event.StorefrontItemsUpdated")
	proto.RegisterType((*StorefrontItemsRetrieved)(nil), "event.StorefrontItemsRetrieved")
	proto.RegisterType((*RetrieveItems)(nil), "event.RetrieveItems")
	proto.RegisterType((*SearchItems)(nil), "event.SearchItems")
	proto.RegisterType((*ItemsRetrieved)(nil), "event.ItemsRetrieved")
	proto.RegisterType((*ItemsSearched)(nil), "event.ItemsSearched")
	proto.RegisterType((*ReviewItem)(nil), "event.ReviewItem")
	proto.RegisterType((*RetrieveItemReviews)(nil), "event.RetrieveItemReviews")
	proto.RegisterType((*CommentItemReview)(nil), "event.CommentItemReview")
	proto.RegisterType((*RetrieveItemReviewComments)(nil), "event.RetrieveItemReviewComments")
	proto.RegisterType((*ItemReviewed)(nil), "event.ItemReviewed")
	proto.RegisterType((*ItemReviewsRetrieved)(nil), "event.ItemReviewsRetrieved")
	proto.RegisterType((*ItemReviewCommented)(nil), "event.ItemReviewCommented")
	proto.RegisterType((*ItemReviewCommentsRetrieved)(nil), "event.ItemReviewCommentsRetrieved")
}

func init() { proto.RegisterFile("events/store.proto", fileDescriptor_4f52bba9433e5948) }

var fileDescriptor_4f52bba9433e5948 = []byte{
	// 1568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0x37, 0xa9, 0x47, 0xe2, 0xa1, 0x24, 0xcb, 0x2b, 0x5b, 0xa6, 0xe5, 0x38, 0x7f, 0x9b, 0xc1,
	0x1f, 0x35, 0x8c, 0xc6, 0x2e, 0x1c, 0x14, 0x45, 0xd1, 0x47, 0xe2, 0x44, 0x0a, 0x62, 0xa0, 0x8e,
	0xd3, 0x95, 0x9d, 0x02, 0xb9, 0x10, 0x8c, 0xb8, 0xb6, 0x08, 0x5b, 0xa2, 0xbb, 0x24, 0x1d, 0xf4,
	0x13, 0x04, 0x68, 0x8b, 0xe6, 0x50, 0xf4, 0xde, 0x6b, 0xbf, 0x41, 0xd1, 0x63, 0x8f, 0xbd, 0xf4,
	0xd8, 0x9e, 0xfa, 0x15, 0x7a, 0xef, 0xa9, 0xd8, 0x07, 0xc5, 0xa7, 0x1c, 0xd9, 0x69, 0x9b, 0x5c,
	0x04, 0xce, 0xec, 0xcc, 0xee, 0x6f, 0x7e, 0x33, 0x3b, 0xbb, 0x2b, 0x40, 0xe4, 0x8c, 0x0c, 0x7d,
	0x6f, 0xd3, 0xf3, 0x5d, 0x4a, 0x36, 0x4e, 0xa9, 0xeb, 0xbb, 0xa8, 0xc4, 0x75, 0xad, 0x25, 0xeb,
	0xe8, 0x88, 0x92, 0x23, 0xcb, 0x27, 0x72, 0x78, 0xd3, 0xf1, 0xc9, 0x40, 0xd8, 0xb4, 0x1a, 0x23,
	0x3f, 0xcb, 0x0f, 0x3c, 0xa9, 0x6c, 0xc5, 0x3c, 0x02, 0x8f, 0x50, 0xfe, 0x23, 0xc7, 0x8c, 0xdc,
	0xd9, 0x4c, 0x4a, 0xce, 0x1c, 0xf2, 0x4c, 0xda, 0xfc, 0x3f, 0x63, 0x23, 0x86, 0xcd, 0x9e, 0x3b,
	0x18, 0x90, 0xa1, 0x2f, 0xcd, 0x56, 0x33, 0x66, 0xfc, 0xf7, 0x90, 0xba, 0xa1, 0x89, 0xf1, 0x6b,
	0x01, 0x66, 0xb7, 0x6d, 0xbb, 0x3b, 0xd2, 0xef, 0xf8, 0x64, 0x80, 0xea, 0x50, 0x08, 0x1c, 0x5b,
	0x57, 0x56, 0x94, 0xb5, 0x69, 0xcc, 0x3e, 0x11, 0x82, 0xe2, 0xd0, 0x1a, 0x10, 0xbd, 0xc8, 0x55,
	0xfc, 0x1b, 0x35, 0xa1, 0x6c, 0x0d, 0xdc, 0x60, 0xe8, 0xeb, 0xa5, 0x15, 0x65, 0xad, 0x84, 0xa5,
	0xc4, 0x6c, 0x83, 0xa1, 0xe3, 0xeb, 0x65, 0x61, 0xcb, 0xbe, 0xd1, 0x1c, 0x94, 0x4e, 0xa9, 0xd3,
	0x23, 0xfa, 0x15, 0x6e, 0x2a, 0x04, 0xb4, 0x02, 0x9a, 0x4d, 0xbc, 0x1e, 0x75, 0x4e, 0x7d, 0xc7,
	0x1d, 0xea, 0x57, 0xb9, 0x43, 0x5c, 0xc5, 0xfd, 0xfa, 0xae, 0xef, 0xea, 0xd3, 0x7c, 0x4c, 0x08,
	0x68, 0x15, 0x2a, 0xc7, 0x81, 0x6d, 0x1d, 0x3b, 0xa6, 0xef, 0x1e, 0x93, 0xa1, 0x0e, 0xc2, 0x51,
	0xe8, 0xf6, 0x99, 0x0a, 0xdd, 0x87, 0x1a, 0x5f, 0xc3, 0xb4, 0x03, 0x6a, 0xf1, 0xd9, 0xb5, 0x15,
	0x65, 0xad, 0xb6, 0xf5, 0xbf, 0x8d, 0x88, 0x94, 0x0d, 0x91, 0xcc, 0x47, 0xcc, 0xae, 0x2d, 0xcd,
	0x70, 0xf5, 0x34, 0x2e, 0xb2, 0x20, 0x4f, 0xc8, 0xf0, 0xc8, 0xef, 0xeb, 0x15, 0x11, 0xa4, 0x90,
	0x18, 0xb0, 0x67, 0x8e, 0xed, 0xf7, 0xf5, 0xaa, 0x08, 0x88, 0x0b, 0xcc, 0xba, 0x4f, 0x9c, 0xa3,
	0xbe, 0xaf, 0xd7, 0x84, 0xb5, 0x90, 0x50, 0x17, 0x1a, 0x8c, 0x06, 0xd3, 0x3d, 0x34, 0x07, 0xc4,
	0xf2, 0x02, 0x4a, 0x58, 0x9a, 0xf4, 0x19, 0x0e, 0xe9, 0x46, 0x16, 0xd2, 0xc1, 0xd0, 0xf1, 0xdd,
	0xc3, 0xdd, 0xc8, 0x14, 0xcf, 0x32, 0xff, 0xbd, 0xb8, 0x8a, 0x41, 0xe8, 0xb9, 0x27, 0x2e, 0xd5,
	0xeb, 0x82, 0x1b, 0x2e, 0x18, 0x7d, 0x98, 0x6b, 0x93, 0x13, 0xe2, 0x93, 0x97, 0xe6, 0x74, 0x09,
	0xa6, 0x79, 0x69, 0x05, 0x4c, 0xaf, 0x72, 0xfd, 0x55, 0xa6, 0x38, 0x60, 0x83, 0x69, 0x8a, 0x8b,
	0x19, 0x8a, 0x8d, 0x3f, 0x0b, 0x30, 0x77, 0x70, 0x6a, 0x5b, 0x13, 0x2c, 0x95, 0x9e, 0x4d, 0xcd,
	0x26, 0x2c, 0x81, 0xa6, 0x90, 0x42, 0xf3, 0x66, 0x95, 0x5f, 0xb6, 0xb6, 0xe0, 0x15, 0x6b, 0x4b,
	0xcb, 0xaf, 0xad, 0x4a, 0x7e, 0x6d, 0x55, 0x27, 0xa9, 0xad, 0xda, 0x3f, 0x53, 0x5b, 0x33, 0xf1,
	0xda, 0xfa, 0x45, 0x81, 0x05, 0x4c, 0x7c, 0xea, 0x90, 0xb3, 0x54, 0xce, 0xbd, 0xcb, 0x25, 0xfd,
	0x2d, 0x98, 0x89, 0x5a, 0x52, 0x3c, 0xf5, 0xb5, 0x48, 0xcd, 0x0b, 0xa0, 0x09, 0x65, 0xf7, 0xf0,
	0xd0, 0x23, 0x3e, 0x2f, 0x81, 0x12, 0x96, 0x12, 0xc3, 0x79, 0xe2, 0x0c, 0x9c, 0xb0, 0x06, 0x84,
	0x80, 0x6e, 0x40, 0x95, 0x12, 0x2f, 0x38, 0xf1, 0x4d, 0xaf, 0xd7, 0x27, 0x03, 0x8b, 0xd7, 0x42,
	0x05, 0x57, 0x84, 0xb2, 0xcb, 0x75, 0xc6, 0xcf, 0x2a, 0x34, 0x92, 0x41, 0x6c, 0xdb, 0x36, 0xb1,
	0x73, 0x02, 0x59, 0x87, 0x22, 0xab, 0x44, 0x1e, 0x80, 0xb6, 0xd5, 0xcc, 0x52, 0xca, 0x9c, 0x31,
	0xb7, 0x41, 0xef, 0x40, 0x85, 0x77, 0x7c, 0x53, 0x34, 0x7c, 0x1e, 0x8e, 0xb6, 0x55, 0xdd, 0xe0,
	0xca, 0x8d, 0x2e, 0x57, 0x62, 0x8d, 0x4b, 0x42, 0x40, 0x0f, 0xa0, 0x61, 0xd9, 0xb6, 0x19, 0xe3,
	0x81, 0x2f, 0x56, 0xe4, 0x8e, 0xba, 0x74, 0xcc, 0xf4, 0x68, 0x3c, 0x6b, 0x65, 0xda, 0xf6, 0x2d,
	0x98, 0xa6, 0xe4, 0xf3, 0x80, 0x78, 0x3e, 0xa1, 0x9c, 0x10, 0x6d, 0x6b, 0x3e, 0x0e, 0x96, 0x9f,
	0x32, 0x07, 0x1e, 0xa1, 0x38, 0xb2, 0x43, 0x1f, 0x02, 0x44, 0x4b, 0x73, 0xa2, 0xb4, 0xad, 0x6b,
	0xd9, 0x10, 0xa3, 0xa5, 0x70, 0xcc, 0xde, 0x78, 0xa1, 0xc2, 0x7c, 0x12, 0x85, 0x68, 0x3e, 0xff,
	0x3d, 0x8d, 0x89, 0xe0, 0x8b, 0x13, 0x06, 0xff, 0x29, 0x34, 0x6d, 0x8e, 0x37, 0x43, 0xbf, 0xa0,
	0x6f, 0x49, 0x2e, 0x98, 0xd7, 0x51, 0xf1, 0x9c, 0x9d, 0xa3, 0x35, 0x7e, 0x57, 0xa1, 0x99, 0xda,
	0x1b, 0xa2, 0x49, 0xe6, 0x51, 0xf2, 0x3e, 0x54, 0xd8, 0x6a, 0x9e, 0xf9, 0x94, 0x1c, 0xba, 0x94,
	0xe8, 0xea, 0x4a, 0xe1, 0x1c, 0x6a, 0x34, 0x6e, 0x7b, 0x97, 0x9b, 0xa2, 0xf7, 0x40, 0x88, 0xa6,
	0x75, 0xc8, 0x22, 0x2e, 0x9c, 0xeb, 0x09, 0xdc, 0x74, 0x9b, 0x59, 0x66, 0xa8, 0x2d, 0x5e, 0x8c,
	0xda, 0xd2, 0xe4, 0xd4, 0x06, 0x3c, 0xee, 0x0c, 0xb5, 0xe5, 0x04, 0xb5, 0x79, 0x27, 0x08, 0x9e,
	0x0b, 0x72, 0xb4, 0xc6, 0x73, 0x15, 0xf4, 0x14, 0xb5, 0x61, 0x37, 0xca, 0x23, 0x37, 0x01, 0x5b,
	0x9d, 0x10, 0xf6, 0xc5, 0x0b, 0xef, 0x09, 0x2c, 0x52, 0x89, 0x22, 0x1d, 0x6a, 0x48, 0xee, 0x75,
	0xe9, 0x3e, 0xa6, 0x77, 0xe2, 0x05, 0x3a, 0xa6, 0xa9, 0x36, 0xa1, 0x2c, 0x7a, 0x16, 0xa7, 0xbd,
	0x82, 0xa5, 0x64, 0x50, 0xa8, 0x86, 0x73, 0x8d, 0xeb, 0xbe, 0x51, 0xc7, 0x54, 0xf3, 0x3b, 0x66,
	0x21, 0xde, 0x31, 0x27, 0x38, 0xee, 0xbf, 0x54, 0x40, 0xeb, 0x12, 0x8b, 0xf6, 0xfa, 0xaf, 0xd0,
	0xf0, 0x75, 0xb8, 0x72, 0x4c, 0xbe, 0x78, 0xe6, 0xd2, 0xb0, 0xd1, 0x87, 0xe2, 0xc5, 0x3a, 0xbc,
	0xf1, 0x93, 0x0a, 0xb5, 0x97, 0x16, 0xc0, 0xc5, 0x28, 0xb8, 0x54, 0x03, 0x49, 0x97, 0x4b, 0xe9,
	0xa5, 0xe5, 0x12, 0xa5, 0xb4, 0x1c, 0x4f, 0x29, 0xfa, 0x00, 0x6a, 0xa3, 0x32, 0x12, 0xb5, 0x73,
	0x85, 0xcf, 0x35, 0x97, 0xaa, 0x1d, 0x11, 0x75, 0x95, 0x26, 0xd2, 0xff, 0x36, 0x94, 0x84, 0xcf,
	0xd5, 0x73, 0xdb, 0x80, 0x30, 0x32, 0x7e, 0x53, 0xa0, 0xca, 0xfd, 0x44, 0x3a, 0x5f, 0xe7, 0xe6,
	0x89, 0xd8, 0x28, 0x26, 0xd8, 0x78, 0x17, 0x2a, 0x1e, 0x07, 0x27, 0xb9, 0x10, 0xbc, 0xa2, 0x70,
	0xa6, 0xa8, 0x0c, 0xb1, 0xe6, 0x45, 0x82, 0xf1, 0x8d, 0x02, 0x80, 0xf9, 0x53, 0xe8, 0xf2, 0x17,
	0x51, 0x06, 0xc9, 0xf2, 0x9d, 0xe1, 0x11, 0x87, 0xaf, 0x62, 0x29, 0x25, 0x2f, 0xa8, 0xc5, 0xd4,
	0x05, 0x95, 0xc7, 0xc1, 0xd6, 0xe5, 0x48, 0xa7, 0xb1, 0x94, 0x8c, 0xef, 0x14, 0x68, 0xc4, 0x33,
	0x27, 0xc0, 0x79, 0xff, 0xc2, 0x15, 0xf9, 0x62, 0xfb, 0xe7, 0x6b, 0x05, 0x66, 0xef, 0x89, 0xc7,
	0x62, 0x04, 0xeb, 0xd2, 0x5b, 0x5a, 0x3e, 0x3b, 0xc3, 0x2d, 0x2d, 0x45, 0xb4, 0x06, 0xf5, 0xd8,
	0xdb, 0x35, 0x4e, 0x5c, 0xcd, 0x19, 0x2d, 0xca, 0xc0, 0x1b, 0x3f, 0x28, 0xd0, 0xca, 0xd2, 0x24,
	0x01, 0x5e, 0x92, 0xad, 0xbc, 0xd5, 0x0b, 0x79, 0xab, 0x5f, 0x90, 0xba, 0xbf, 0x14, 0xa8, 0x44,
	0x18, 0x5f, 0xe7, 0xe6, 0xf9, 0x48, 0x5c, 0x01, 0x64, 0x84, 0xb2, 0x67, 0x5d, 0x1b, 0xb3, 0xf7,
	0xb9, 0x8d, 0xb8, 0x08, 0xc8, 0x6c, 0x6f, 0x81, 0x26, 0xb9, 0x89, 0xdd, 0x78, 0x66, 0x47, 0xed,
	0x26, 0xdc, 0x45, 0x18, 0xe8, 0xe8, 0xdb, 0xf8, 0x51, 0x85, 0xb9, 0x58, 0x1d, 0xbf, 0x01, 0xc7,
	0xef, 0xb8, 0x0e, 0xf2, 0x10, 0xe6, 0x13, 0xfd, 0x54, 0xb2, 0x14, 0xb6, 0x92, 0x56, 0x4e, 0x5b,
	0x0d, 0x83, 0x6a, 0xd0, 0x9c, 0x1d, 0x7b, 0x5b, 0x5c, 0xd5, 0x46, 0xd3, 0x94, 0x79, 0xa7, 0x3d,
	0x9f, 0x6d, 0x2d, 0x62, 0xdb, 0x33, 0xbe, 0x57, 0xa1, 0x91, 0xa9, 0xed, 0xd7, 0xc9, 0xdc, 0x7d,
	0x76, 0xe2, 0xc4, 0xff, 0x36, 0x92, 0x15, 0x94, 0xf3, 0x8c, 0x4d, 0x60, 0x66, 0x87, 0x4f, 0x4c,
	0x64, 0x0f, 0x18, 0x39, 0x41, 0x9c, 0x68, 0xc9, 0x73, 0xf8, 0x80, 0xc9, 0x34, 0x1b, 0x3c, 0xdb,
	0x4b, 0xab, 0x8c, 0x3f, 0x54, 0x58, 0xca, 0x6e, 0xff, 0x37, 0xa0, 0xc8, 0x1e, 0xc0, 0x4c, 0x92,
	0x2a, 0x76, 0xb3, 0x2b, 0x4c, 0xc2, 0x55, 0x8d, 0x26, 0x5b, 0x99, 0x0d, 0xcb, 0x79, 0x65, 0x19,
	0xcd, 0x2b, 0x68, 0x5b, 0x1d, 0x5b, 0x9e, 0x23, 0x56, 0x5a, 0x74, 0x7c, 0xc3, 0x1c, 0x73, 0xc9,
	0x58, 0x7f, 0xa1, 0xc0, 0x72, 0x74, 0xc7, 0xec, 0x12, 0x7a, 0xe6, 0xf4, 0x08, 0xf3, 0xb2, 0x86,
	0xf6, 0xbe, 0x7b, 0xea, 0xf4, 0xd0, 0x02, 0x34, 0xb6, 0xdb, 0x6d, 0xb3, 0xbb, 0xbf, 0x87, 0x3b,
	0xf7, 0xf1, 0xde, 0xc3, 0x7d, 0x73, 0x67, 0xbf, 0xb3, 0x5b, 0x9f, 0x42, 0x2d, 0x68, 0xb6, 0x3b,
	0x9f, 0x74, 0xf6, 0x3b, 0x99, 0x31, 0x85, 0x8d, 0x1d, 0x3c, 0x6a, 0x6f, 0xe7, 0x8c, 0xa9, 0x68,
	0x19, 0x16, 0x71, 0x67, 0x1f, 0xef, 0x74, 0x1e, 0x67, 0x46, 0xbb, 0xf5, 0xc2, 0xfa, 0xb7, 0x0a,
	0x2c, 0x65, 0x10, 0x75, 0x58, 0xec, 0x02, 0xcf, 0x22, 0xcc, 0xa7, 0xbc, 0xcc, 0xed, 0x76, 0xbb,
	0xd3, 0xae, 0x4f, 0xa1, 0x25, 0x58, 0x48, 0x0f, 0x09, 0x84, 0xed, 0xba, 0x82, 0xae, 0x81, 0x9e,
	0x5e, 0xcd, 0x14, 0x18, 0xdb, 0x75, 0x15, 0x5d, 0x87, 0x56, 0x66, 0x34, 0x44, 0xd9, 0xae, 0x17,
	0xd6, 0x6f, 0xc3, 0x02, 0x63, 0x35, 0x8f, 0x20, 0x04, 0xb5, 0x51, 0x3c, 0x22, 0x88, 0x29, 0x54,
	0x87, 0x4a, 0xb7, 0xb3, 0x8d, 0xef, 0x3d, 0x90, 0x1a, 0x65, 0xfd, 0x0e, 0xcc, 0xc7, 0x26, 0x88,
	0xc5, 0xd3, 0x80, 0x99, 0xf4, 0x72, 0x53, 0x6c, 0x4e, 0xa1, 0x14, 0xb3, 0xb0, 0x00, 0xd6, 0x9f,
	0x2b, 0xb0, 0x1c, 0x65, 0x36, 0x0f, 0xc9, 0x0c, 0x68, 0xb8, 0xf3, 0x78, 0xa7, 0xf3, 0x59, 0x98,
	0xa2, 0x45, 0x98, 0x4f, 0x40, 0x33, 0xc5, 0x70, 0xb7, 0xae, 0xb0, 0xb4, 0xde, 0xdb, 0xdb, 0xdd,
	0xed, 0x84, 0x44, 0x89, 0x91, 0xba, 0x8a, 0x56, 0x61, 0x39, 0xcf, 0xc7, 0x94, 0xd6, 0x2c, 0x45,
	0x5f, 0x29, 0xf1, 0x5d, 0x99, 0x0d, 0x69, 0x16, 0xaa, 0x31, 0x4f, 0x1e, 0x50, 0x0b, 0x9a, 0x71,
	0x00, 0xb1, 0x60, 0x15, 0x86, 0x32, 0x67, 0x21, 0x9e, 0x16, 0x03, 0xae, 0xe7, 0x61, 0x88, 0xa7,
	0xe6, 0xee, 0x9d, 0x27, 0x1f, 0x1f, 0x39, 0x7e, 0x3f, 0x78, 0xba, 0xd1, 0x73, 0x07, 0x9b, 0xce,
	0x49, 0xdf, 0x1a, 0x0c, 0xfa, 0xb6, 0xbd, 0x29, 0x8e, 0xfe, 0x9b, 0xd1, 0x0b, 0xec, 0xa6, 0x27,
	0x90, 0x6e, 0x06, 0x1e, 0xe9, 0x59, 0x1e, 0xf1, 0x36, 0xc5, 0x5f, 0xf1, 0x4f, 0xcb, 0xfc, 0xaf,
	0xef, 0x5b, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xac, 0x2b, 0x34, 0x6c, 0xd3, 0x17, 0x00, 0x00,
}
